import streamlit as st

option = st.selectbox(
    'Unsur Kimia',
    ('golongan IA','golongan IIA','golongan IIIB','golongan IVB','golongan VB','golongan VIB','golongan VIIB','golongan VIII','golongan IB','golongan IIB','golongan IIIA','golongan IVA','golongan VA','golongan VIA','golongan VIIA','golongan VIIIA')
)

if option == "golongan IA":
    tab1,tab2,tab3,tab4,tab5,tab6,tab7,tab8=st.tabs(['hidrogen','litium','Natrium','Kalium','Rubidium','Cesium','fransium','Ununennium'])
    tab1.title('Nama Latin:')
    tab1.write('Hydrogenium')
    tab1.title('Tahun ditemukan:')
    tab1.write('1766')
    tab1.title('penemu:')
    tab1.write('Henry Cavendish')
    
    tab1.title('Catatan:')
    tab1.write('Hidrogen adalah unsur kimia Non Logam dengan simbol kimia H dan nomor atom 1, dengan berat atom 1.00784u, hidrogen adalah unsur paling ringan di tabel periodik. Bentuk monatomik (H) adalah zat kimia paling melimpah di alam semesta, yang membentuk sekitar 75% dari semua massa baronik.')
    tab1.title('Nomor Atom:')
    tab1.write('1')
    tab1.title('Massa Atom Relatif:')
    tab1.write('1.007970942025939(g/mol)')
    tab1.title('Densitas:')
    tab1.write('0.00008988(g/cm^3)')
    tab1.title('Titik Leleh:')
    tab1.write('-259.16°C=-434.49°F=13.99k')
    tab1.title('Titik didih:')
    tab1.write('-252.879°C=-434.49°F=20.27k')
    tab1.title('Fase:')
    tab1.write('Gas')
    tab1.title('Periode:')
    tab1.write('1')

    tab2.title('Nama Latin:')
    tab2.write('Lithium')
    tab2.title('Tahun ditemukan:')
    tab2.write('1817')
    tab2.title('Penemu:')
    tab2.write('Johan August Arfwedson')
    
    
    tab2.title('Catatan:')
    tab2.write('Litium adalah elemen kimia dengan simbol Li dan nomor atom 3. ini adalah logam lunak, perak-putih milik kelompok logam alkali dari unsur unsur kimia. Dalam kondisi standar itu adalah logam paling ringan dan unsur paling padat.')

    tab2.title('Nomor Atom:')
    tab2.write('3')
    tab2.title('Massa Atom Relatif:')
    tab2.write('6.96746072811231(g/mol)')
    tab2.title('Densitas')
    tab2.write('0.534(g/cm^3)')
    tab2.title('Titik Leleh:')
    tab2.write('180.5°C=356.9°F=453.65k')
    tab2.title('Titik didih:')
    tab2.write('1330.0°C=2426.0°F=1603.15k')
    tab2.title('Fase:')
    tab2.write('Padat')
    tab2.title('Periode:')
    tab2.write('2')

    tab3.title('Nama Latin:')
    tab3.write('Natrium')
    tab3.title('Tahun ditemukan:')
    tab3.write('11807')
    tab3.title('Penemu:')
    tab3.write('Humphy Davy')
    
    tab3.title('Catatan:')
    tab3.write('Natrium (sodium) adalah elemen kimia dengan simbol Na dan nomor atom 11. ini adalah logam lunak, perak-putih, sangat reaktif. Dalam tabel periodik terdapat di kolom 1(logam alkali), dan berbagi dengan enam elemen lainnya dalam kolom yang memiliki elektron tunggal dikulit terluarnya, yang siap disumbangkan, menciptakan atom bermuatan positif-kation')

    tab3.title('Nomor Atom:')
    tab3.write('11')
    tab3.title('Massa Atom Relatif:')
    tab3.write('22.9897692819791(g/mol)')
    tab3.title('Densitas:')
    tab3.write('0.968(g/cm^3)')
    tab3.title('Titik Leleh:')
    tab3.write('95.794°C=208.03°F=370.94k')
    tab3.title('Titik didih:')
    tab3.write('882.94°C=1621.29°F=1156.09k')
    tab3.title('Fase:')
    tab3.write('Padat')
    tab3.title('Periode:')
    tab3.write('3')

    tab4.title('Nama Latin:')
    tab4.write('kalium')
    tab4.title('Tahun ditemukan:')
    tab4.write('1807')
    tab4.title('Penemu:')
    tab4.write('Humphy Davy')
    
    tab4.title('Catatan:')
    tab4.write('Kalium adalah unsur kimia dengan simbol K dan nomor atom 19.Dalam tabel periodik, kalium adalah salah satu dari tujuh elemen dalam kolom (grup) 1 (logam alkali): mereka semua memiliki elektron valensi tunggal dalam kulit elektron terluarnya, yang siap mereka hilangkan untuk membuat atom dengan muatan positif-a kationm, dan kombinasikan dengan anion untuk membentuk garam.')

    tab4.title('Nomor Atom:')
    tab4.write('19')
    tab4.title('Massa Atom Relatif:')
    tab4.write('39.0983009088233(g/mol)')
    tab4.title('Densitas:')
    tab4.write('0.89(g/cm^3))')
    tab4.title('Titik Leleh:')
    tab4.write('63.5°C=146.3°F=336.65k')
    tab4.title('Titik didih:')
    tab4.write('759.0°C=1398.2°F=1032.15k')
    tab4.title('Fase:')
    tab4.write('Padat')
    tab4.title('Periode:')
    tab4.write('4')


    tab5.title('Nama Latin:')
    tab5.write('Rubidium')
    tab5.title('Tahun ditemukan:')
    tab5.write('1861')
    tab5.title('Penemu:')
    tab5.write('Robet Wilhelm Bunsen, Gustav Robert Kirchoff')

    tab5.title('Catatan:')
    tab5.write('Rubidium adalah elemen kimia dengan simbol Rb dan nomor atom 37, rubidium adalah elemen logam lunak, keperakan-putih dari kelompok logam alkali, dengan massa atom 85,4678. Rubidium Unsur sangat reaktif, dengan sifat-sifat yang mirip dengan logam alkali lainnya, seperti oksidasi yang sangat cepat di udara.')

    tab5.title('Nomor Atom:')
    tab5.write('37')
    tab5.title('Massa Atom Relatif:')
    tab5.write('85.46476635933375(g/mol)')
    tab5.title('Densitas:')
    tab5.write('1.532(g/cm^3)')
    tab5.title('Titik Leleh:')
    tab5.write('39.3°C=102.74°F=312.45k')
    tab5.title('Titik didih:')
    tab5.write('688.0°C=1270.4°F=961.15k')
    tab5.title('Fase:')
    tab5.write('Padat')
    tab5.title('Periode:')
    tab5.write('5')

    tab6.title('Nama Latin:')
    tab6.write('Caesium')
    tab6.title('Tahun ditemukan:')
    tab6.write('1860')
    tab6.title('Penemu:')
    tab6.write('Robet Wilhelm Bunsen, Gustav Robert Kirchoff')
    
    tab6.title('Catatan:')
    tab6.write('Cesium adalah elemen kimia dengan simbol Cs dan nomor atom 55. Ini adalah logam alkali yang lembut, berwarna emas keperakan dengan titik leleh 28 C yang menjadikannya salah satu dari hanya loma logam unsur yang cairan pada atau dekat suhu kamar. cesium adalah logam alkali dan memiliki sifat fisik dan kimia yang mirip dengan rubidium dan kalium.')
    
    tab6.title('Nomor Atom:')
    tab6.write('55')
    tab6.title('Massa Atom Relatif:')
    tab6.write('132.905451958556(g/mol)')
    tab6.title('Densitas:')
    tab6.write('1.93(g/cm^3))')
    tab6.title('Titik Leleh:')
    tab6.write('28.5°C=88.3°F=301.65k')
    tab6.title('Titik didih:')
    tab6.write('671.0°C=1239.8°F=944.15k')
    tab6.title('Fase:')
    tab6.write('Padat')
    tab6.title('Periode:')
    tab6.write('6')

    tab7.title('Nama Latin:')
    tab7.write('Francium')
    tab7.title('Tahun ditemukan:')
    tab7.write('1939')
    tab7.title('Penemu:')
    tab7.write('Marguerite Perey')
    tab7.title('Catatan:')

    tab7.write('Fransium adalah elemen kimi dengan simbol Fr dan nomor atom 87. Duku dikenal sebagai eka- cesium dan actinium K. ini adalah elemen elektronegatif kedua, di belakang hanya cesium. Francium adalah logam yang sangat radioaktif yang meluruh menjadi astatin, tadium, dan radon')

    tab7.title('Nmor Atom:')
    tab7.write('87')
    tab7.title('Massa Atom Relatif:')
    tab7.write('223.01973(g/mol)')
    tab7.title('Densitas:')
    tab7.write('1.87(g/cm^3)')
    tab7.title('Titik Leleh:')
    tab7.write('27.0°C=80.6°F=300.15k')
    tab7.title('Titik didih:')
    tab7.write('677.0°C=1250.6°F=950.15k')
    tab7.title('Fase:')
    tab7.write('Padat')
    tab7.title('Periode:')
    tab7.write('7')
    
    tab8.title('Nama Latin:')
    tab8.write('Ununennium')
    tab8.title('Tahun ditemukan:')
    tab8.write('~2006')
    tab8.title('Penemu:')
    tab8.write('Joint Institute For Nuclear Research (JINR),Lawrence Livermore National Laboratory(LLNL)')
    tab8.title('Catatan:')
    tab8.write('Ununenium, juga dikenal sebagai eka-francium, atau lebih dikenal sebagai elemen 119, adalah elemen kimia hipotetis dengan simbol Uue dan nomor atom 119. Ununenium dan Uue masing-masing adalah nama dan simbol IUPAC sementara, yang digunakan hingga elemen tersebut ditemukan, dikonfirmasi dan nama permanen diputuskan. Unsur ini akan berada di posisi pertama dalam periode ke-8, dengan sifat-sifat yang mungkin mirip dengan logam alkali milik blok s. Karena efek relativistik yang menekan orbital 8-nya, itu akan menjadi kurang reaktif daripada francium dan cesium, dan akan memiliki sifat kimia yang lebih dekat dengan rubidium pada periode ke-5 daripada dengan francium pada periode ke-7, dan jari-jari atomnya akan menjadi dari urutan yang sama dengan francium.')
    tab8.title('Nomor Atom:')
    tab8.write('119')
    tab8.title('Massa Atom Relatif:')
    tab8.write('316(g/mol)')
    tab8.title('Densitas:')
    tab8.write('7(g/cm^3)')
    tab8.title('Titik Leleh:')
    tab8.write('30.0°C = 86.0°F = 303.15K')
    tab8.title('Titik didih:')
    tab8.write('630.0°C = 1166.0°F = 903.15K')
    tab8.title('Fase:')
    tab8.write('Cair')
    tab8.title('Periode:')
    tab8.write('8')


elif option == "golongan IIA":
    tab1,tab2,tab3,tab4,tab5,tab6,tab7=st.tabs(['Berilium','Magnesium','Kalsium','Strontium','Barium','Radium','Unbinilium'])
    tab1.title('Nama Latin:')
    tab1.write('Beryllium')
    tab1.title('Tahun ditemukan:')
    tab1.write('1798')
    tab1.title('Penemu:')
    tab1.write('Louis-Nicolas Vauquelin')
    tab1.title('Catatan:')
    tab1.write('Berilium adalah unsur kimia dengan simbol Be dan nomor atom 4. Berilium diciptakan melalui nukleosintesis bintang dan merupakan unsur yang relatif langka di alam semesta. ini adalah eleen divalen yang terjadi secara alami hanya dalam kombinasi dengan elemen lain dalam mineral.')
    tab1.title('Nomor Atom:')
    tab1.write('4')
    tab1.title('Massa Atom Relatif:')
    tab1.write('9.01218306156802(g/mol)')
    tab1.title('Densitas:')
    tab1.write('1.85(g/cm^3))')
    tab1.title('Titik Leleh:')
    tab1.write('1287.0°C=2348.6°F=1560.15k')
    tab1.title('Titik didih:')
    tab1.write('2469.0°C=4476.2°F=2742.15k')
    tab1.title('Fase:')
    tab1.write('Padat')
    tab1.title('Periode:')
    tab1.write('2')

    tab2.title('Nama Latin:')
    tab2.write('Magnesium')
    tab2.title('Tahun ditemukan:')
    tab2.write('1755')
    tab2.title('Penemu:')
    tab2.write('Joseph Blck,Humphry Davy')
    tab2.title('Catatan:')
    tab2.write('Magnesium adalah elemen kimia dengan simbol Mg dan nomor atom 12. ini adalah padatan abu-abu mengkilap yang memiliki kemiripan fisik yang dekat dengan lima elemen lainnya di kolom kedua (logam alkali tanah),magnesium adalah unsur kesembilan paling berlimbah di alam semesta')
    tab2.title('Nomor Atom:')
    tab2.write('12')
    tab2.title('Massa Atom Relatif:')
    tab2.write('24.3050516136388(g/mol)')
    tab2.title('Densitas:')
    tab2.write('1.738(g/cm^3)')
    tab2.title('Titik Leleh:')
    tab2.write('650.0°C=1202.0°F=923.15k')
    tab2.title('Titik didih:')
    tab2.write('1090.0°C=1994.0°F=1363.15k')
    tab2.title('Fase:')
    tab2.write('Padat')
    tab2.title('Periode:')
    tab2.write('3')

    tab3.title('Nama Latin:')
    tab3.write('Calcium')
    tab3.title('Tahun ditemukan:')
    tab3.write('1808')
    tab3.title('Penemu:')
    tab3.write('Humphry Davy')
    tab3.title('Catatan:')
    
    tab3.write('Kalsium adalah elemen kimia dengan simbol Ca dan nomor atom 20. Kalsium adalah logam alkali tanah abu-abu yang lembut, unsur kelima yang paling berlimpah oleh massa di kerak bumi. lon Ca2 + juga merupakan ion terlarut kelima terbanyak di air laut oleh molaritas dan massa, setelah natrium, klorida, magnesium, dan sulfat.')

    tab3.title('Nomor Atom:')
    tab3.write('20')
    tab3.title('Massa Atom Relatif:')
    tab3.write('40.0780224976209(g/mol)')
    tab3.title('Densitas:')
    tab3.write('1.55(g/cm^3)')
    tab3.title('Titik Leleh:')
    tab3.write('842.0°C=1547.6°F=1115.15k')
    tab3.title('Titik didih:')
    tab3.write('1484.0°C=2703.2°F=1757.15k')
    tab3.title('Fase:')
    tab3.write('Padat')
    tab3.title('Periode:')
    tab3.write('4')

    tab4.title('Nama Latin:')
    tab4.write('Strontium')
    tab4.title('Tahun ditemukan:')
    tab4.write('1787')
    tab4.title('Penemu:')
    tab4.write('Adair Crawford')
    tab4.title('Catatan:')
    tab4.write('Strontium adalah elemen kimia dengan simbol Sr dan nomor atom 38. Sebuah logam alkali tanah, strontium adalah elemen logam perak-putih atau kekuningan lunak yang sangat reaktif secara kimiawi. Logam berubah menjadi kuning saat terkena udara')
    tab4.title('Nomor Atom:')
    tab4.write('38')
    tab4.title('Massa Atom Relatif:')
    tab4.write('87.616442781531(g/mol)')
    tab4.title('Densitas:')
    tab4.write('2.64(g/cm^3)')
    tab4.title('Titik Leleh:')
    tab4.write('777.0°C=1430.6°F=1050.15k')
    tab4.title('Titik didih:')
    tab4.write('1382.0°C=2519.6°F=1655.15k')
    tab4.title('Fase:')
    tab4.write('Padat')
    tab4.title('Periode:')
    tab4.write('5')

    tab5.title('Nama Latin:')
    tab5.write('Barium')
    tab5.title('Tahun ditemukan:')
    tab5.write('1774')
    tab5.title('Penemu:')
    tab5.write('Humphry Davy')
    tab5.title('Catatan:')
    tab5.write('Barium adalah elemen kimia dengan simbol Ba dan nomor atom 56. Ini adalah elemen kelima dalam Grup 2, logam alkali tanah logam lunak berwarna keperakan. Karena reaktivitas kimianya yang tinggi, barium tidak pernah ditemukan di alam sebagai unsur bebas.')
    tab5.title('Nomor Atom:')
    tab5.write('56')
    tab5.title('Massa Atom Relatif:')
    tab5.write('137.32667172235(g/mol)')
    tab5.title('Densitas:')
    tab5.write('3.51(g/cm^3)')
    tab5.title('Titik Leleh:')
    tab5.write('727.0°C=1340.6°F=1000.15k')
    tab5.title('Titik didih:')
    tab5.write('1637.0°C=2978.6°F=1910.15k')
    tab5.title('Fase:')
    tab5.write('Padat')
    tab5.title('Periode:')
    tab5.write('6')


    tab6.title('Nama Latin:')
    tab6.write('Radium')
    tab6.title('Tahun ditemukan:')
    tab6.write('1898')
    tab6.title('Penemu:')
    tab6.write('Pierre Curie, Marie Sklodowska Curie')
    tab6.title('Catatan:')
    tab6.write('Radium adalah elemen kimia dengan simbol Ra dan nomor atom 88. Ini adalah elemen keenam dalam grup 2 dari tabel periodik, juga dikenal sebagai logam alkali tanah. Radium murni hampir tidak berwarna, tetapi mudah bergabung dengan nitrogen (daripada oksigen) pada paparan udara, membentuk lapisan permukaan hitam radium nitrida (Ra3N2).')
    tab6.title('Nomor Atom:')
    tab6.write('88')
    tab6.title('Massa Atom Relatif:')
    tab6.write('226.032494020223(g/mol)')
    tab6.title('Densitas:')
    tab6.write('5.5(g/cm^3)')
    tab6.title('Titik Leleh:')
    tab6.write('700.0°C=1292.0°F=973.15k')
    tab6.title('Titik didih:')
    tab6.write('1737.0°C=3158.6°F=2010.15k')
    tab6.title('Fase:')
    tab6.write('Padat')
    tab6.title('Periode:')
    tab6.write('7')
    
    tab7.title('Nama Latin:')
    tab7.write('Unbinilium')
    tab7.title('Tahun ditemukan:')
    tab7.write('≈2006-2008')
    tab7.title('Penemu:')
    tab7.write('Joint institute for Nuclear Research (JINR), RIKEN (理研)')
    tab7.title('Catatan:')
    tab7.write('Unbinilium, juga dikenal sebagai eka-radium, atau lebih dikenal sebagai elemen 120, adalah elemen kimia hipotetis dengan simbol Ubn dan nomor atom 120. Unbinilium dan Ubn masing-masing adalah nama sementara dan simbol IUPAC, yang digunakan hingga elemen tersebut ditemukan, dikonfirmasi dan nama permanen diputuskan. Ini dimaksudkan untuk menjadi elemen blok, logam alkali tanah, dan elemen kedua dari periode kedelapan. la telah menarik perhatian karena beberapa prediksi bahwa ia mungkin berada di pulau stabilitas, meskipun perhitungan yang lebih baru memperkirakan bahwa pulau itu sebenarnya berada pada nomor atom yang sedikit lebih rendah, lebih dekat ke copernicium dan flerovium.')
    tab7.title('Nomor Atom:')
    tab7.write('120')
    tab7.title('Massa Atom Relatif:')
    tab7.write('320(g/mol)')
    tab7.title('Densitas:')
    tab7.write('7(g/cm^3)')
    tab7.title('Titik Leleh:')
    tab7.write('680.0°C =1256.0°F =953.15 K')
    tab7.title('Titik didih:')
    tab7.write('1700.0°C =3092.0°F =1973.15 K')
    tab7.title('Fase:')
    tab7.write('-')
    tab7.title('Periode:')
    tab7.write('8')

elif option == 'golongan IIIB':
    tab1,tab2=st.tabs(['scandium','Itrium'])
    tab1.title('Nama Latin:')
    tab1.write('Scandium ')
    tab1.title('Tahun ditemukan:')
    tab1.write('1879')
    tab1.title('Penemu:')
    tab1.write('Lars Fredrik Nilson')
    tab1.title('Catatan:')
    tab1.write('Skandium adalah unsur kimia;  ia memiliki simbol Sc dan nomor atom 21. Ia adalah unsur blok d metalik berwarna putih keperakan.  Secara historis, ia telah diklasifikasikan sebagai unsur tanah jarang,[9] bersama dengan yttrium dan lantanida.  Ditemukan pada tahun 1879 melalui analisis spektral mineral euxenite dan gadolinite dari Skandinavia.')
    tab1.title('Nomor Atom:')
    tab1.write('21')
    tab1.title('Massa Atom Relatif:')
    tab1.write('44.9559070745661(g/mol)')
    tab1.title('Densitas:')
    tab1.write('2.985(g/cm^3)')
    tab1.title('Titik Leleh:')
    tab1.write('1541.0°C = 2805.8°F = 1814.15K')
    tab1.title('Titik didih:')
    tab1.write('2836.0°C = 5136.8°F = 3109.15K')
    tab1.title('Fase:')
    tab1.write('Padat')
    tab1.title('Periode:')
    tab1.write('4')

    tab2.title('Nama Latin:')
    tab2.write('Yttrium')
    tab2.title('Tahun ditemukan:')
    tab2.write('1794')
    tab2.title('Penemu:')
    tab2.write('Johan Gadolin')
    tab2.title('Catatan:')
    tab2.write('Itrium adalah unsur kimia;  ia memiliki simbol Y dan nomor atom 39. Ia adalah logam transisi keperakan-logam yang secara kimia mirip dengan lantanida dan sering diklasifikasikan sebagai "unsur tanah jarang".  Yttrium hampir selalu ditemukan dalam kombinasi dengan unsur lantanida dalam mineral tanah jarang dan tidak pernah ditemukan di alam sebagai unsur bebas. 89Y adalah satu-satunya isotop stabil dan satu-satunya isotop yang ditemukan di kerak bumi.')
    tab2.title('Nomor Atom:')
    tab2.write('39')
    tab2.title('Massa Atom Relatif:')
    tab2.write('88.9058381585322(g/mol)')
    tab2.title('Densitas:')
    tab2.write('4.472 (g/cm^3)')
    tab2.title('Titik Leleh:')
    tab2.write('1526.0°C = 2778.8°F = 1799.15K')
    tab2.title('Titik didih:')
    tab2.write('2930.0°C = 5306.0°F = 3203.15K')
    tab2.title('Fase:')
    tab2.write('Padat')
    tab2.title('Periode:')
    tab2.write('5')

elif option == "golongan IVB":
    tab1,tab2,tab3,tab4=st.tabs(['Titanium','Zirconium','Hafnium','Rutherfordium'])
    tab1.title('Nama Latin:')
    tab1.write('Titanium')
    tab1.title('Tahun ditemukan:')
    tab1.write('1791')
    tab1.title('Penemu:')
    tab1.write('William Gregor')
    tab1.title('Catatan:')
    tab1.write('Titanium adalah unsur kimia;  mempunyai simbol Ti dan nomor atom 22. Ditemukan di alam hanya sebagai oksida, dapat direduksi menghasilkan logam transisi berkilau dengan warna perak, kepadatan rendah, dan kekuatan tinggi, tahan terhadap korosi pada air laut, aqua regia, dan klorin.')
    tab1.title('Nomor Atom:')
    tab1.write('22')
    tab1.title('Massa Atom Relatif:')
    tab1.write('47.8667436596202(g/mol)')
    tab1.title('Densitas:')
    tab1.write('4.506 (g/cm^3)')
    tab1.title('Titik Leleh:')
    tab1.write('1668.0°C = 3034.4°F = 1941.15K')
    tab1.title('Titik didih:')
    tab1.write('3287.0°C = 5948.6°F = 3560.15K')
    tab1.title('Fase:')
    tab1.write('Padat')
    tab1.title('Periode:')
    tab1.write('4')

    tab2.title('Nama Latin:')
    tab2.write('Zirconium')
    tab2.title('Tahun ditemukan:')
    tab2.write('1789')
    tab2.title('Penemu:')
    tab2.write('Martin Heinrich Klaproth')
    tab2.title('Catatan:')
    tab2.write('Zirkonium adalah unsur kimia;  ia memiliki simbol Zr dan nomor atom 40. Nama zirkonium diambil dari nama mineral zirkon, sumber zirkonium terpenting.  Kata ini ada hubungannya dengan zargun Persia (zirkon; zar-gun, "seperti emas" atau "seperti emas").[8]  Ini adalah logam transisi kuat berwarna abu-abu putih yang sangat mirip dengan hafnium dan, pada tingkat lebih rendah, titanium.')
    tab2.title('Nomor Atom:')
    tab2.write('40')
    tab2.title('Massa Atom Relatif:')
    tab2.write('91.2236427905792(g/mol)')
    tab2.title('Densitas:')
    tab2.write('6.52(g/cm^3)')
    tab2.title('Titik Leleh:')
    tab2.write('1855.0°C = 3371.0°F = 2128.15K')
    tab2.title('Titik didih:')
    tab2.write('4377.0°C = 7910.6°F = 4650.15K')
    tab2.title('Fase:')
    tab2.write('Padat')
    tab2.title('Periode:')
    tab2.write('5')

    tab3.title('Nama Latin:')
    tab3.write('Hafnium')
    tab3.title('Tahun ditemukan:')
    tab3.write('1922')
    tab3.title('Penemu:')
    tab3.write('Martin Heinrich Klaproth')
    tab3.title('Catatan:')
    tab3.write('Hafnium adalah unsur kimia;  ia memiliki simbol Hf dan nomor atom 72. Logam transisi tetravalen berwarna abu-abu keperakan berkilau, hafnium secara kimia menyerupai zirkonium dan ditemukan di banyak mineral zirkonium.  Keberadaannya telah diprediksi oleh Dmitri Mendeleev pada tahun 1869, meskipun baru teridentifikasi pada tahun 1922 oleh Dirk Coster dan George de Hevesy, menjadikannya salah satu dari dua unsur stabil terakhir yang ditemukan.  (Unsur renium ditemukan pada tahun 1908 oleh Masataka Ogawa, meskipun nomor atomnya salah diidentifikasi pada saat itu, dan secara umum tidak diakui oleh komunitas ilmiah sampai ditemukan kembali oleh Walter Noddack, Ida Noddack, dan Otto Berg pada tahun 1925. Hal ini membuat  agak sulit untuk mengatakan apakah hafnium atau renium ditemukan terakhir kali.)[10] Nama Hafnium diambil dari nama Hafnia, nama Latin untuk Kopenhagen, tempat ia ditemukan.')
    tab3.title('Nomor Atom:')
    tab3.write('72')
    tab3.title('Massa Atom Relatif:')
    tab3.write('178.484981221495(g/mol)')
    tab3.title('Densitas:')
    tab3.write('13,31(g/cm^3)')
    tab3.title('Titik Leleh:')
    tab3.write('2233.0°C = 4051.4°F = 2506.15K')
    tab3.title('Titik didih:')
    tab3.write('4603.0°C = 8317.4°F = 4876.15K')
    tab3.title('Fase:')
    tab3.write('Padat')
    tab3.title('Periode:')
    tab3.write('6')

    tab4.title('Nama Latin:')
    tab4.write('Rutherfordium')
    tab4.title('Tahun ditemukan:')
    tab4.write('1969')
    tab4.title('Penemu:')
    tab4.write('Georgiy Flerov')
    tab4.title('Catatan:')
    tab4.write('Rutherfordium adalah unsur kimia sintetis;  ia memiliki simbol Rf dan nomor atom 104. Namanya diambil dari nama fisikawan Ernest Rutherford.  Sebagai unsur sintetik, unsur ini tidak ditemukan di alam dan hanya dapat dibuat dalam akselerator partikel.  Itu bersifat radioaktif;  isotop paling stabil yang diketahui, 267Rf, memiliki waktu paruh sekitar 48 menit.')
    tab4.title('Nomor Atom:')
    tab4.write('104 ')
    tab4.title('Massa Atom Relatif:')
    tab4.write('266.32341341081(g/mol)')
    tab4.title('Densitas :')
    tab4.write('-')
    tab4.title('Titik Leleh:')
    tab4.write('2100.0°C = 3812.0°F = 2373.15K')
    tab4.title('Titik didih:')
    tab4.write('-')
    tab4.title('Fase:')
    tab4.write('Padat')
    tab4.title('Periode:')
    tab4.write('7')

elif option == "golongan VB":
    tab1,tab2,tab3,tab4=st.tabs(['Vanadium','Niobium','Tantalum','Dubnium'])
    tab1.title('Nama Latin:')
    tab1.write('Vanadium')
    tab1.title('Tahun ditemukan:')
    tab1.write('1801')
    tab1.title('Penemu:')
    tab1.write('Andres Manuel del Rio')
    tab1.title('Catatan:')
    tab1.write('Vanadium adalah elemen kimia dengan simbol V dan nomor atom 23. Ini adalah logam transisi yang keras, berwarna abu-abu keperakan, ulet dan mudah ditempa. Unsur ini hanya ditemukan dalam bentuk gabungan kimia di alam, tetapi setelah diisolasi secara buatan, pembentukan lapisan oksida menstabilkan logam bebas agak melawan oksidasi lebih lanjut.')
    tab1.title('Nomor Atom:')
    tab1.write('23')
    tab1.title('Massa Atom Relatif:')
    tab1.write('50.9414656566912(g/mol)')
    tab1.title('Densitas :')
    tab1.write(' 6.11 (g/cm^3)')
    tab1.title('Titik Leleh:')
    tab1.write('1910.0°C =3470.0 °F =2183.15 K')
    tab1.title('Titik didih:')
    tab1.write('3407.0°C = 6164.6°F = 3680.15K')
    tab1.title('Fase:')
    tab1.write('Padat')
    tab1.title('Periode:')
    tab1.write('4')

    tab2.title('Nama Latin:')
    tab2.write('Niobium')
    tab2.title('Tahun ditemukan:')
    tab2.write('1801')
    tab2.title('Penemu:')
    tab2.write('Charles Hatchett')
    tab2.title('Catatan:')
    tab2.write('Niobium, sebelumnya columbium, adalah unsur kimia dengan simbol Nb (sebelumnya Cb) dan nomor atom 41. Ini adalah logam transisi yang lunak, abu-abu, dan ulet, yang sering ditemukan dalam mineral piroklor, sumber komersial utama untuk niobium, dan columbite. Nama ini berasal dari mitologi Yunani: Niobe, putri Tantalus karena sangat mirip dengan tantalum.')
    tab2.title('Nomor Atom:')
    tab2.write('41')
    tab2.title('Massa Atom Relatif:')
    tab2.write('92.9063732129128(g/mol)')
    tab2.title('densitas :')
    tab2.write(' 8.57(g/cm^3)')
    tab2.title('Titik Leleh:')
    tab2.write('2477.0°C = 4490.6°F = 2750.15K')
    tab2.title('Titik didih:')
    tab2.write('4744.0°C = 8571.2°F = 5017.15K')
    tab2.title('Fase:')
    tab2.write('Padat')
    tab2.title('Periode:')
    tab2.write('5')
    
    tab3.title('Nama Latin:')
    tab3.write('Tantalum')
    tab3.title('Tahun ditemukan:')
    tab3.write('1802')
    tab3.title('Penemu:')
    tab3.write('Andres Gustaf Ekeberg')
    tab3.title('Catatan:')
    tab3.write('Tantalum adalah elemen kimia dengan simbol Ta dan nomor atom 73. Sebelumnya dikenal sebagai tantalium, namanya berasal dari Tantalus, antihero dari mitologi Yunani. Tantalum adalah logam transisi langka, keras, biru-abu-abu, berkilau yang sangat tahan korosi.')
    tab3.title('Nomor Atom:')
    tab3.write('73')
    tab3.title('Massa Atom Relatif:')
    tab3.write('180.947878335825(g/mol)')
    tab3.title('Densitas :')
    tab3.write('16.69(g/cm^3)')
    tab3.title('Titik Leleh:')
    tab3.write('3017.0°C = 5462.6°F = 3290.15K')
    tab3.title('Titik didih:')
    tab3.write('5458.0°C = 9856.4°F = 5731.15K')
    tab3.title('Fase:')
    tab3.write('Padat')
    tab3.title('Periode:')
    tab3.write('6')

    tab4.title('Nama Latin:')
    tab4.write('Dubnium')
    tab4.title('Tahun ditemukan:')
    tab4.write('1970')
    tab4.title('Penemu:')
    tab4.write('Georgiy Flerov')
    tab4.title('Catatan:')
    tab4.write('Dubnium adalah elemen kimia dengan simbol Db dan nomor atom 105. Dinamai kota Dubna di Rusia (utara Moskow), tempat ia pertama kali diproduksi. Ini adalah elemen sintetis (elemen yang dapat dibuat di laboratorium tetapi tidak ditemukan di alam) dan radioaktif; isotop yang dikenal paling stabil, dubnium-268, memiliki waktu paruh sekitar 28 jam.')
    tab4.title('Nomor Atom:')
    tab4.write('105')
    tab4.title('Massa Atom Relatif:')
    tab4.write('268/142818454282(g/mol)')
    tab4.title('Densitas:')
    tab4.write('-')
    tab4.title('Titik Leleh:')
    tab4.write('-')
    tab4.title('Titik didih:')
    tab4.write('-')
    tab4.title('Fase:')
    tab4.write('Padat')
    tab4.title('Periode:')
    tab4.write('7')

elif option == "golongan VIB":
    tab1,tab2,tab3,tab4=st.tabs(['Krom','Molibden','Tungsten','Seaborgium'])
    tab1.title('Nama Latin:')
    tab1.write('Chromium')
    tab1.title('Tahun ditemukan:')
    tab1.write('1794')
    tab1.title('Penemu:')
    tab1.write('Louis-Nicolas Vauquelin')
    tab1.title('Catatan:')
    tab1.write('Chromium adalah elemen kimia dengan simbol Cr dan nomor atom 24. Ini adalah elemen pertama di Grup 6. Ini adalah baja abu-abu, berkilau, keras dan rapuh yang membutuhkan polesan tinggi, tahan noda, dan memiliki titik lebur tinggi.')
    tab1.title('Nomor Atom:')
    tab1.write('24')
    tab1.title('Massa Atom Relatif:')
    tab1.write('51.9961302818614(g/mol)')
    tab1.title('Densitas:')
    tab1.write('7.15(g/cm^3)')
    tab1.title('Titik Leleh:')
    tab1.write('1907.0°C = 3464.6°F = 2180.15K')
    tab1.title('Titik didih:')
    tab1.write('2482.0°C = 4499.6°F = 2755.15K')
    tab1.title('Fase:')
    tab1.write('Padat')
    tab1.title('Periode:')
    tab1.write('4')

    tab2.title('Nama Latin:')
    tab2.write('Molybdaenum')
    tab2.title('Tahun ditemukan:')
    tab2.write('1778')
    tab2.title('Penemu:')
    tab2.write('Carl Wilhelm Scheele')
    tab2.title('Catatan:')
    tab2.write('Molibdenum adalah unsur kimia dengan simbol Mo dan nomor atom 42. Nama ini berasal dari molybdaenum Neo-Latin, dari Ancientλυβδος molybdos Yunani Kuno, yang berarti timah, karena bijihnya dikacaukan dengan bijih timah. Mineral molibdenum telah dikenal sepanjang sejarah, tetapi unsur itu ditemukan (dalam arti membedakannya sebagai entitas baru dari garam mineral logam lain) pada 1778 oleh Carl Wilhelm Scheele.')
    tab2.title('Nomor Atom:')
    tab2.write('42')
    tab2.title('Massa Atom Relatif:')
    tab2.write('95.9487770772113(g/mol)')
    tab2.title('Densitas:')
    tab2.write('10.28(g/cm^3)')
    tab2.title('Titik Leleh:')
    tab2.write('2623.0°C = 4753.4°F = 2896.15K')
    tab2.title('Titik didih:')
    tab2.write('4639.0°C = 8382.2°F = 4912.15K')
    tab2.title('Fase:')
    tab2.write('Padat')
    tab2.title('Periode:')
    tab2.write('5')
    
    tab3.title('Nama Latin:')
    tab3.write('Wolframium')
    tab3.title('Tahun ditemukan:')
    tab3.write('1781')
    tab3.title('Penemu:')
    tab3.write('Carl Wilhelm Scheele')
    tab3.title('Catatan:')
    tab3.write('Tungsten, juga dikenal sebagai wolfram, adalah elemen kimia dengan simbol W dan nomor atom 74. Kata tungsten berasal dari bahasa Swedia tung sten, yang secara langsung diterjemahkan menjadi batu berat. Namanya dalam bahasa Swedia adalah volfram, untuk membedakannya dari scheelite, yang dalam bahasa Swedia disebut tungsten.')
    tab3.title('Nomor Atom:')
    tab3.write('74')
    tab3.title('Massa Atom Relatif:')
    tab3.write('183.841779591731(g/mol)')
    tab3.title('Densitas:')
    tab3.write('19.25(g/cm^3)')
    tab3.title('Titik Leleh:')
    tab3.write('3422.0°C = 6191.6°F = 3695.15K')
    tab3.title('Titik didih:')
    tab3.write('5930.0°C = 10706.0°F = 6203.15K')
    tab3.title('Fase:')
    tab3.write('Padat')
    tab3.title('Periode:')
    tab3.write('6')

    tab4.title('Nama Latin:')
    tab4.write('Seaborhium')
    tab4.title('Tahun ditemukan:')
    tab4.write('1974')
    tab4.title('Penemu:')
    tab4.write('Georgiy Flerov')
    tab4.title('Catatan:')
    tab4.write('Seaborgium adalah elemen sintetis dengan simbol Sg dan nomor atom 106. Isotopnya yang paling stabil 271Sg memiliki waktu paruh 1,9 menit. Isotop 269Sg yang lebih baru ditemukan memiliki waktu paruh yang mungkin sedikit lebih lama.')
    tab4.title('Nomor Atom:')
    tab4.write('106')
    tab4.title('Massa Atom Relatif:')
    tab4.write('270.486936755388(g/mol)')
    tab4.title('Densitas:')
    tab4.write('-')
    tab4.title('Titik Leleh:')
    tab4.write('-')
    tab4.title('Titik didih:')
    tab4.write('-')
    tab4.title('Fase:')
    tab4.write('Padat')
    tab4.title('Periode:')
    tab4.write('7')

elif option == "golongan VIIB":
    tab1,tab2,tab3,tab4=st.tabs(['Mangan','Teknesium','Renium','Bohrium'])
    tab1.title('Nama Latin:')
    tab1.write('Manganum')
    tab1.title('Tahun ditemukan:')
    tab1.write('1774')
    tab1.title('Penemu:')
    tab1.write('Johan Gottkieb Gahn')
    tab1.title('Catatan:')
    tab1.write('Mangan adalah unsur kimia dengan simbol Mn dan nomor atom 25. Mangan tidak ditemukan sebagai unsur bebas di alam; sering ditemukan dalam kombinasi dengan zat besi, dan dalam banyak mineral. Mangan adalah logam dengan penggunaan logam campuran industri yang penting, terutama pada baja tahan karat.')
    tab1.title('Nomor Atom:')
    tab1.write('25')
    tab1.title('Massa Atom Relatif:')
    tab1.write('54.9380430430528(g/mol)')
    tab1.title('Densitas:')
    tab1.write('7.21(g/cm^3)')
    tab1.title('Titik Leleh:')
    tab1.write('1246.0°C = 2274.8°F = 1519.15K')
    tab1.title('Titik didih:')
    tab1.write('2062.0°C = 3741.8°F = 2334.15K')
    tab1.title('Fase:')
    tab1.write('Padat')
    tab1.title('Periode:')
    tab1.write('4')

    tab2.title('Nama Latin:')
    tab2.write('Technetium')
    tab2.title('Tahun ditemukan:')
    tab2.write('1937')
    tab2.title('Penemu:')
    tab2.write('Emilio Gino Segre, Carlo Perrier')
    tab2.title('Catatan:')
    tab2.write('Technetium (tekni:fiəm) adalah elemen kimia dengan simbol Tc dan nomor atom 43. Ini adalah elemen dengan nomor atom terendah dalam tabel periodik yang tidak memiliki isotop stabil: setiap bentuknya adalah radioaktif. Hampir semua teknesium diproduksi secara sintetis, dan hanya jumlah kecil yang ditemukan di alam.')
    tab2.title('Nomor Atom:')
    tab2.write('43')
    tab2.title('Massa Atom Relatif:')
    tab2.write('97.4429222893571(g/mol)')
    tab2.title('Densitas:')
    tab2.write('11.0(g/cm^3)')
    tab2.title('Titik Leleh:')
    tab2.write('2157.0°C = 3914.6°F = 2430.15K')
    tab2.title('Titik didih:')
    tab2.write('4265.0°C = 7709.0°F = 4538.15K')
    tab2.title('Fase:')
    tab2.write('Padat')
    tab2.title('Periode:')
    tab2.write('5')
    
    tab3.title('Nama Latin:')
    tab3.write('Rhenium')
    tab3.title('Tahun ditemukan:')
    tab3.write('1908')
    tab3.title('Penemu:')
    tab3.write('-')
    tab3.title('Catatan:')
    tab3.write('Renium adalah elemen kimia dengan simbol Re dan nomor atom 75. Ini adalah logam transisi putih baris keperakan, berat, ketiga pada kelompok 7 dari tabel periodik. Dengan perkiraan konsentrasi rata-rata 1 bagian per miliar (ppb), renium adalah salah satu unsur paling langka di kerak bumi.')
    tab3.title('Nomor Atom:')
    tab3.write('75')
    tab3.title('Massa Atom Relatif:')
    tab3.write('186.206707351458(g/mol)')
    tab3.title('Densitas:')
    tab3.write('21.02(g/cm^3)')
    tab3.title('Titik Leleh:')
    tab3.write('3186.0°C = 5766.8°F = 3459.15K')
    tab3.title('Titik didih:')
    tab3.write('5596.0°C = 10104.8°F = 5869.15K')
    tab3.title('Fase:')
    tab3.write('Padat')
    tab3.title('Periode:')
    tab3.write('6')

    tab4.title('Nama Latin:')
    tab4.write('Bohrium')
    tab4.title('Tahun ditemukan:')
    tab4.write('1981')
    tab4.title('Penemu:')
    tab4.write('Peter Armbruster')
    tab4.title('Catatan:')
    tab4.write('Bohrium adalah elemen kimia dengan simbol Bh dan nomor atom 107. Dinamai dari fisikawan Denmark Niels Bohr. Ini adalah elemen sintetis (elemen yang dapat dibuat di laboratorium tetapi tidak ditemukan di alam) dan radioaktif; isotop yang diketahui paling stabil, 270Bh, memiliki waktu paruh sekitar 61 detik.')
    tab4.title('Nomor Atom:')
    tab4.write('107')
    tab4.title('Massa Atom Relatif:')
    tab4.write('270.929231154427(g/mol)')
    tab4.title('Densitas:')
    tab4.write('-')
    tab4.title('Titik Leleh:')
    tab4.write('-')
    tab4.title('Titik didih:')
    tab4.write('-')
    tab4.title('Fase:')
    tab4.write('Padat')
    tab4.title('Periode:')
    tab4.write('7')
    
elif option == "golongan VIII":
    tab1,tab2,tab3,tab4,tab5,tab6,tab7,tab8,tab9,tab10,tab11,tab12=st.tabs(['Besi','Rutenium','Osmium','Hasium','Cobalt','Rodium','Iridium','Meitnerium','Nikel','Paladium','Platina','Darmstadtium'])
    tab1.title('Nama Latin:')
    tab1.write('Ferrum')
    tab1.title('Tahun ditemukan:')
    tab1.write('5000 BC')
    tab1.title('Penemu:')
    tab1.write('-')
    tab1.title('Catatan:')
    tab1.write('Besi adalah elemen kimia dengan simbol Fe (dari bahasa Latin: ferrum) dan nomor atom 26. Ini adalah logam dalam seri transisi pertama. Ini adalah massa elemen yang paling umum di Bumi, membentuk banyak inti luar dan dalam Bumi.')
    tab1.title('Nomor Atom:')
    tab1.write('26')
    tab1.title('Massa Atom Relatif:')
    tab1.write('55.8451436425238 (g/mol)')
    tab1.title('Densitas:')
    tab1.write('7.86 (g/cm^3)')
    tab1.title('Titik Leleh:')
    tab1.write('1538.0°C = 2800.4°F = 1811.15K')
    tab1.title('Titik didih:')
    tab1.write('2861.0°C = 5181.8°F = 3134.15K')
    tab1.title('Fase:')
    tab1.write('Padat')
    tab1.title('Periode:')
    tab1.write('4')

    tab2.title('Nama Latin:')
    tab2.write('Ruthenium')
    tab2.title('Tahun ditemukan:')
    tab2.write('1844')
    tab2.title('Penemu:')
    tab2.write('Karl Ernst Claus')
    tab2.title('Catatan:')
    tab2.write('Rutenium adalah unsur kimia dengan simbol Ru dan nomor atom 44. Ini adalah logam transisi langka yang termasuk dalam kelompok platinum dari tabel periodik. Seperti logam lain dari kelompok platinum, ruthenium lembam untuk sebagian besar bahan kimia lainnya.')
    tab2.title('Nomor Atom:')
    tab2.write('44')
    tab2.title('Massa Atom Relatif:')
    tab2.write('101.064936840548 (g/mol)')
    tab2.title('Densitas :')
    tab2.write('12.45(g/cm^3)')
    tab2.title('Titik Leleh:')
    tab2.write('2334.0°C = 4233.2°F = 2607.15K')
    tab2.title('Titik didih:')
    tab2.write('4150.0°C = 7502.0°F = 4423.15K')
    tab2.title('Fase:')
    tab2.write('Padat')
    tab2.title('Periode:')
    tab2.write('5')
    
    tab3.title('Nama Latin:')
    tab3.write('Osmium')
    tab3.title('Tahun ditemukan:')
    tab3.write('1803')
    tab3.title('Penemu:')
    tab3.write('Smithson Tennant')
    tab3.title('Catatan:')
    tab3.write('Osmium adalah elemen kimia dengan simbol O dan nomor atom 76. Ini adalah logam transisi keras, rapuh, putih kebiruan dalam kelompok platinum yang ditemukan sebagai elemen jejak dalam paduan, sebagian besar dalam bijih platinum. Osmium adalah unsur terpadat yang terjadi secara alami, dengan kepadatan 22,59 g / cm³.')
    tab3.title('Nomor Atom:')
    tab3.write('76')
    tab3.title('Massa Atom Relatif:')
    tab3.write('190.22486145925(g/mol)')
    tab3.title('Densitas:')
    tab3.write('22.59 (g/cm^3)')
    tab3.title('Titik Leleh:')
    tab3.write('3033.0°C = 5491.4°F =3306.15 K')
    tab3.title('Titik didih:')
    tab3.write('5012.0°C = 9053.6°F = 5285.15K')
    tab3.title('Fase:')
    tab3.write('Padat')
    tab3.title('Periode:')
    tab3.write('6')

    tab4.title('Nama Latin:')
    tab4.write('Hassium')
    tab4.title('Tahun ditemukan:')
    tab4.write('1984')
    tab4.title('Penemu:')
    tab4.write('GSI(Helmholtzzentrum fur schwerionenforschung')
    tab4.title('Catatan:')
    tab4.write('Hassium adalah unsur kimia dengan simbol Hs dan nomor atom 108, dinamai negara bagian Hesse Jerman. Ini adalah elemen sintetis (elemen yang dapat dibuat di laboratorium tetapi tidak ditemukan di alam) dan radioaktif; isotop yang diketahui paling stabil, 269Hs, memiliki waktu paruh sekitar 9,7 detik, meskipun keadaan metastabil yang belum dikonfirmasi, 277mHs, mungkin memiliki paruh lebih lama sekitar 130 detik. Lebih dari 100 atom hassium telah disintesis hingga saat ini.')
    tab4.title('Nomor Atom:')
    tab4.write('108')
    tab4.title('Massa Atom Relatif:')
    tab4.write('275.381591197533(g/mol)')
    tab4.title('Densitas kg*m^-3:')
    tab4.write('-')
    tab4.title('Titik Leleh:')
    tab4.write('-')
    tab4.title('Titik didih:')
    tab4.write('-')
    tab4.title('Fase:')
    tab4.write('Padat')
    tab4.title('Periode:')
    tab4.write('7')
    
    tab5.title('Nama Latin:')
    tab5.write('Cobaltum')
    tab5.title('Tahun ditemukan:')
    tab5.write('1735')
    tab5.title('Penemu:')
    tab5.write('Georg Brandt')
    tab5.title('Catatan:')
    tab5.write('Cobalt adalah elemen kimia dengan simbol Co dan nomor atom 27. Seperti nikel, kobalt di kerak bumi hanya ditemukan dalam bentuk gabungan kimia, kecuali untuk lapisan kecil yang ditemukan dalam paduan besi meteorik alami. Unsur bebas, yang dihasilkan oleh peleburan reduktif, adalah logam keras, berkilau, perak-abu-abu.')
    tab5.title('Nomor Atom:')
    tab5.write('27')
    tab5.title('Massa Atom Relatif:')
    tab5.write('58.9331935652212(g/mol)')
    tab5.title('Densitas:')
    tab5.write('8.9 (g/cm^3)')
    tab5.title('Titik Leleh:')
    tab5.write('1495.0°C = 2725.0°F = 1768.15K')
    tab5.title('Titik didih:')
    tab5.write('2927.0°C = 5300.6°F = 3200.15K')
    tab5.title('Fase:')
    tab5.write('Padat')
    tab5.title('Periode:')
    tab5.write('4')
    
    tab6.title('Nama Latin:')
    tab6.write('Rhodium')
    tab6.title('Tahun ditemukan:')
    tab6.write('1804')
    tab6.title('Penemu:')
    tab6.write('William Hyde Wollaston')
    tab6.title('Catatan:')
    tab6.write('Rhodium adalah elemen kimia dengan simbol Rh dan nomor atom 45. Ini adalah logam transisi yang langka, putih keperakan, keras, dan lembam secara kimia. Itu adalah anggota kelompok platinum')
    tab6.title('Nomor Atom:')
    tab6.write('45')
    tab6.title('Massa Atom Relatif:')
    tab6.write('102.905494087647(g/mol)')
    tab6.title('Densitas :')
    tab6.write('12.41 (g/cm^3)')
    tab6.title('Titik Leleh:')
    tab6.write('1964.0°C = 3567.2°F = 2237.15K')
    tab6.title('Titik didih:')
    tab6.write('3695.0°C = 6683.0°F = 3969.15K')
    tab6.title('Fase:')
    tab6.write('Padat')
    tab6.title('Periode:')
    tab6.write('5')
    
    tab7.title('Nama Latin:')
    tab7.write('Iridium')
    tab7.title('Tahun ditemukan:')
    tab7.write('1803')
    tab7.title('Penemu:')
    tab7.write('Smithson Tennant')
    tab7.title('Catatan:')
    tab7.write('Iridium adalah unsur kimia dengan simbol Ir dan nomor atom 77. Logam transisi yang sangat keras, rapuh, putih keperakan dari kelompok platinum, iridium umumnya dianggap sebagai unsur terpadat kedua (setelah osmium) berdasarkan kepadatan yang diukur, walaupun perhitungan melibatkan kisi ruang elemen menunjukkan bahwa iridium lebih padat. Ini juga merupakan logam yang paling tahan korosi, bahkan pada suhu setinggi 2000 ° C. Meskipun hanya garam dan halogen cair tertentu yang bersifat korosif terhadap iridium padat, debu iridium yang terbelah halus jauh lebih reaktif dan dapat terb')
    tab7.title('Nomor Atom:')
    tab7.write('77')
    tab7.title('Massa Atom Relatif:')
    tab7.write('192/216053820407(g/mol)')
    tab7.title('Densitas :')
    tab7.write(' 22.56(g/cm^3)')
    tab7.title('Titik Leleh:')
    tab7.write('2446.0°C = 4434.8°F = 2719.15K')
    tab7.title('Titik didih:')
    tab7.write('4130.0°C = 7466.0°F = 4403.15K')
    tab7.title('Fase:')
    tab7.write('Padat')
    tab7.title('Periode:')
    tab7.write('6')
    
    tab8.title('Nama Latin:')
    tab8.write('Meitnerium')
    tab8.title('Tahun ditemukan:')
    tab8.write('1982')
    tab8.title('Penemu:')
    tab8.write('GSI(Helmholtzzentrum Fur Schwerionenforschung')
    tab8.title('Catatan:')
    tab8.write('Meitnerium adalah elemen kimia dengan simbol Mt dan nomor atom 109. Ini adalah elemen sintetis yang sangat radioaktif (elemen yang tidak ditemukan di alam yang dapat dibuat di laboratorium). Isotop yang diketahui paling stabil, meitnerium-278, memiliki waktu paruh 7,6 detik.')
    tab8.title('Nomor Atom:')
    tab8.write('109')
    tab8.title('Massa Atom Relatif:')
    tab8.write('278.130923401647(g/mol)')
    tab8.title('Densitas:')
    tab8.write('-')
    tab8.title('Titik Leleh:')
    tab8.write('-')
    tab8.title('Titik didih:')
    tab8.write('-')
    tab8.title('Fase:')
    tab8.write('Padat')
    tab8.title('Periode:')
    tab8.write('7')

    tab9.title('Nama Latin:')
    tab9.write('Nicolum')
    tab9.title('Tahun ditemukan:')
    tab9.write('1751')
    tab9.title('Penemu:')
    tab9.write('Axel Frendenic Von Cronstedt')
    tab9.title('Catatan:')
    tab9.write('Nikel adalah unsur kimia dengan simbol Ni dan nomor atom 28. Ini adalah logam berkilau putih keperakan dengan semburat emas sedikit. Nikel milik logam transisi dan keras dan ulet.')
    tab9.title('Nomor Atom:')
    tab9.write('28')
    tab9.title('Massa Atom Relatif:')
    tab9.write('58/6933503482247(g/mol)')
    tab9.title('Densitas:')
    tab9.write('8.908 (g/cm^3)')
    tab9.title('Titik Leleh:')
    tab9.write('1455.0°C = 2651.0°F = 1728.15K')
    tab9.title('Titik didih:')
    tab9.write('2730.0°C = 4946.0°F = 3003.15K')
    tab9.title('Fase:')
    tab9.write('Padat')
    tab9.title('Periode:')
    tab9.write('4')
    
    tab10.title('Nama Latin:')
    tab10.write('Palladium')
    tab10.title('Tahun ditemukan:')
    tab10.write('1803')
    tab10.title('Penemu:')
    tab10.write('William Hyde Wollaston')
    tab10.title('Catatan:')
    tab10.write('Palladium adalah elemen kimia dengan simbol Pd dan nomor atom 46. Ini adalah logam putih keperakan yang langka dan berkilau yang ditemukan pada 1803 oleh William Hyde Wollaston. Dia menamainya dengan asteroid Pallas, yang dengan sendirinya dinamai julukan dewi Yunani Athena, yang diperolehnya ketika dia membunuh Pallas.')
    tab10.title('Nomor Atom:')
    tab10.write('46')
    tab10.title('Massa Atom Relatif:')
    tab10.write('106.415327899964(g/mol)')
    tab10.title('Densitas:')
    tab10.write('12.023(g/cm^3)')
    tab10.title('Titik Leleh:')
    tab10.write('1554.0°C = 2830.82°F = 1828.05K')
    tab10.title('Titik didih:')
    tab10.write('2963.0°C = 5365.4°F = 3236.15K')
    tab10.title('Fase:')
    tab10.write('Padat')
    tab10.title('Periode:')
    tab10.write('5')
    
    tab11.title('Nama Latin:')
    tab11.write('Platina')
    tab11.title('Tahun ditemukan:')
    tab11.write('1735')
    tab11.title('Penemu:')
    tab11.write('Antonio de Ulloa')
    tab11.title('Catatan:')
    tab11.write('Platinum adalah elemen kimia dengan simbol Pt dan nomor atom 78. Ini adalah logam transisi yang padat, mudah ditempa, fleksibel, sangat tidak reaktif, berharga, abu-abu-putih. Namanya berasal dari istilah Spanyol platina, yang secara harfiah diterjemahkan menjadi "sedikit perak ".')
    tab11.title('Nomor Atom:')
    tab11.write('78')
    tab11.title('Massa Atom Relatif:')
    tab11.write('195.084429339468(g/mol)')
    tab11.title('Densitas:')
    tab11.write(' 21.45(g/cm^3)')
    tab11.title('Titik Leleh:')
    tab11.write('1768.3°C = 3214.94°F = 2041.45K')
    tab11.title('Titik didih:')
    tab11.write('3825.0°C = 6917.0°F = 4098.15K')
    tab11.title('Fase:')
    tab11.write('Padat')
    tab11.title('Periode:')
    tab11.write('6')

    tab12.title('Nama Latin:')
    tab12.write('Darmstadtium')
    tab12.title('Tahun ditemukan:')
    tab12.write('1994')
    tab12.title('Penemu:')
    tab12.write('GSI(Helmholtzzentrum fur Schwerionenforschung')
    tab12.title('Catatan:')
    tab12.write('Darmstadtium adalah elemen kimia dengan simbol Ds dan nomor atom 110. Ini adalah elemen sintetis yang sangat radioaktif. Isotop yang diketahui paling stabil, darmstadtium-281, memiliki waktu paruh sekitar 10 detik.')
    tab12.title('Nomor Atom:')
    tab12.write('110')
    tab12.title('Massa Atom Relatif:')
    tab12.write('282.575485574983(g/mol)')
    tab12.title('Densitas:')
    tab12.write('-')
    tab12.title('Titik Leleh:')
    tab12.write('-')
    tab12.title('Titik didih:')
    tab12.write('-')
    tab12.title('Fase:')
    tab12.write('Padat')
    tab12.title('Periode:')
    tab12.write('7')

elif option == "golongan IB":
    tab1,tab2,tab3,tab4=st.tabs(['Tembaga','Perak','Emas','Roentgenium'])
    tab1.title('Nama Latin:')
    tab1.write('Cuprum')
    tab1.title('Tahun ditemukan:')
    tab1.write('9000 BC')
    tab1.title('Penemu:')
    tab1.write('-')
    tab1.title('Catatan:')
    tab1.write('Tembaga adalah unsur kimia;  ia memiliki simbol Cu (dari bahasa Latin cuprum) dan nomor atom 29. Ia adalah logam lunak, mudah dibentuk, dan ulet dengan konduktivitas termal dan listrik yang sangat tinggi. Permukaan tembaga murni yang baru terpapar memiliki warna oranye merah muda. Tembaga digunakan sebagai konduktor panas dan listrik, sebagai bahan bangunan, dan sebagai penyusun berbagai paduan logam, seperti perak murni yang digunakan dalam perhiasan, cupronickel yang digunakan untuk membuat perangkat keras dan koin kelautan, dan konstanta yang digunakan dalam pengukur regangan dan termokopel Untuk pengukuran suhu.')
    tab1.title('Nomor Atom:')
    tab1.write('29')
    tab1.title('Massa Atom Relatif:')
    tab1.write('63.5460394301709(g/mol)')
    tab1.title('Densitas kg*m^-3:')
    tab1.write('8.96 (g/cm^3)')
    tab1.title('Titik Leleh:')
    tab1.write('1084.62°C = 1984.32°F = 1357.77K')
    tab1.title('Titik didih:')
    tab1.write('2562.0°C = 4643.6°F = 2835.15K')
    tab1.title('Fase:')
    tab1.write('Padat')
    tab1.title('Periode:')
    tab1.write('4')

    tab3.title('Nama Latin:')
    tab3.write('Argentum')
    tab3.title('Tahun ditemukan:')
    tab3.write('5000 BC')
    tab3.title('Penemu:')
    tab3.write('-')
    tab3.title('Catatan:')
    tab3.write('Perak adalah unsur kimia;  ia memiliki simbol Ag  dan nomor atom 47. Merupakan logam transisi lunak, putih, berkilau, ia menunjukkan konduktivitas listrik tertinggi, termal  konduktivitas, dan reflektifitas logam apa pun.Logam ini ditemukan di kerak bumi dalam bentuk unsur bebas murni ("perak asli"), sebagai paduan dengan emas dan logam lainnya, dan dalam mineral seperti argentit dan klorargyrit. Kebanyakan perak diproduksi sebagai produk sampingan dari pemurnian tembaga, emas, timah, dan seng.')
    tab3.title('Nomor Atom:')
    tab3.write('47')
    tab3.title('Massa Atom Relatif:')
    tab3.write('107.868149833461(g/mol)')
    tab3.title('Densitas kg*m^-3:')
    tab3.write('10.49 (g/cm^3)')
    tab3.title('Titik Leleh:')
    tab3.write('961.78°C = 1763.2°F = 1234.93K')
    tab3.title('Titik didih:')
    tab3.write('2210.0°C = 4010.0°F = 2483.15K')
    tab3.title('Fase:')
    tab3.write('Padat')
    tab3.title('Periode:')
    tab3.write('5')
    
    tab2.title('Nama Latin:')
    tab2.write('Aurum')
    tab2.title('Tahun ditemukan:')
    tab2.write('6000 BC')
    tab2.title('Penemu:')
    tab2.write('-')
    tab2.title('Catatan:')
    tab2.write('Emas adalah suatu unsur kimia dengan lambang Au (dari kata Latin aurum) dan nomor atom 79. Dalam bentuknya yang murni, emas adalah logam cerah, agak kuning jingga, padat, lunak, mudah dibentuk, dan ulet.  Secara kimia, emas merupakan logam transisi, unsur golongan 11, dan salah satu logam mulia.  Ini adalah salah satu unsur kimia yang paling tidak reaktif, dan merupakan yang terendah kedua dalam rangkaian reaktivitas. Ini solid dalam kondisi standar')
    tab2.title('Nomor Atom:')
    tab2.write('79')
    tab2.title('Massa Atom Relatif:')
    tab2.write('196.966570051362(g/mol)')
    tab2.title('Densitas kg*m^-3:')
    tab2.write('19.3 (Kg/cm^3)')
    tab2.title('Titik Leleh:')
    tab2.write('1064.18°C = 1947.52°F = 1337.33K')
    tab2.title('Titik didih:')
    tab2.write('2970.0°C = 1947.52°F = 3242.15K')
    tab2.title('Fase:')
    tab2.write('Padat')
    tab2.title('Periode:')
    tab2.write('6')

    tab4.title('Nama Latin:')
    tab4.write('Roentgenium')
    tab4.title('Tahun ditemukan:')
    tab4.write('1994')
    tab4.title('Penemu:')
    tab4.write('GSI (Helmholtzzentrum für Schwerionenforschung)')
    tab4.title('Catatan:')
    tab4.write('Roentgenium adalah unsur kimia sintetik;  ia memiliki simbol Rg dan nomor atom 111. Ia sangat radioaktif dan hanya dapat dibuat di laboratorium. Isotop paling stabil yang diketahui, roentgenium-282, memiliki waktu paruh 120 detik, meskipun roentgenium-286 yang belum dikonfirmasi mungkin memiliki waktu paruh lebih lama sekitar 10,7 menit.  Roentgenium pertama kali dibuat pada tahun 1994 oleh Pusat Penelitian Ion Berat GSI Helmholtz dekat Darmstadt, Jerman.  Namanya diambil dari nama fisikawan Wilhelm Röntgen (juga dieja Roentgen), yang menemukan sinar-X. Hanya sedikit atom roentgenium yang pernah disintesis, dan tidak mempunyai penerapan praktis.')
    tab4.title('Nomor Atom:')
    tab4.write('111')
    tab4.title('Massa Atom Relatif:')
    tab4.write('283.085549304907(g/mol)')
    tab4.title('Densitas kg*m^-3:')
    tab4.write('-')
    tab4.title('Titik Leleh:')
    tab4.write('-')
    tab4.title('Titik didih:')
    tab4.write('-')
    tab4.title('Fase:')
    tab4.write('Padat')
    tab4.title('Periode:')
    tab4.write('5')
    
elif option == "golongan IIB":
    tab1,tab2,tab3,tab4=st.tabs(['Seng','Cadmium','Raksa','Kopernisium'])
    tab1.title('Nama Latin:')
    tab1.write('Zincum')
    tab1.title('Tahun ditemukan:')
    tab1.write('1000 BC')
    tab1.title('Penemu:')
    tab1.write('Andreas Sigismud Marggraf')
    tab1.title('Catatan:')
    tab1.write('Seng, dalam perdagangan juga spelter, adalah elemen kimia dengan simbol Zn dan nomor atom 30. Ini adalah elemen pertama dari grup 12 dari tabel periodik. Dalam beberapa hal seng secara kimiawi mirip dengan magnesium: ionnya berukuran sama dan satu-satunya keadaan oksidasi yang umum adalah +2.')
    tab1.title('Nomor Atom:')
    tab1.write('30')
    tab1.title('Massa Atom Relatif:')
    tab1.write('65.3777823033184(g/mol)')
    tab1.title('Densitas, kg*m^-3:')
    tab1.write('7.14(Kg/m^3)')
    tab1.title('Titik Leleh:')
    tab1.write('419.53°C = 787.15°F = 692.68 K')
    tab1.title('Titik didih:')
    tab1.write('907.0°C = 1664.6°F = 1180.15K')
    tab1.title('Fase:')
    tab1.write('Padat')
    tab1.title('Periode:')
    tab1.write('4')

    tab2.title('Nama Latin:')
    tab2.write('Cadmium')
    tab2.title('Tahun ditemukan:')
    tab2.write('1817')
    tab2.title('Penemu:')
    tab2.write('Friedrich Stromeyer')
    tab2.title('Catatan:')
    tab2.write('Kadmium adalah unsur kimia dengan simbol Cd dan nomor atom 48. Logam lunak berwarna putih kebiruan ini secara kimiawi mirip dengan dua logam stabil lainnya dalam kelompok 12, seng dan merkuri. Seperti seng, ia lebih suka keadaan oksidasi +2 di sebagian besar senyawanya dan seperti merkuri itu menunjukkan titik leleh yang rendah dibandingkan dengan logam transisi.')
    tab2.title('Nomor Atom:')
    tab2.write('48')
    tab2.title('Massa Atom Relatif:')
    tab2.write('112.413818634622(g/mol)')
    tab2.title('densitas, kg*m^-3:')
    tab2.write('8.65(Kg/m^3)')
    tab2.title('Titik Leleh:')
    tab2.write('321.07°C = 609.93°F = 594.22 K')
    tab2.title('Titik didih:')
    tab2.write('767.0°C = 1412.6°F = 1040.15K')
    tab2.title('Fase:')
    tab2.write('Padat')
    tab2.title('Periode:')
    tab2.write('5')
    
    tab3.title('Nama Latin:')
    tab3.write('Hydrargyrum')
    tab3.title('Tahun ditemukan:')
    tab3.write('1500 BC')
    tab3.title('Penemu:')
    tab3.write('---')
    tab3.title('Catatan:')
    tab3.write('Merkuri adalah unsur kimia dengan simbol Hg dan nomor atom 80. Biasanya dikenal sebagai quicksilver dan sebelumnya bernama hydrargyrum (/ haıdra:rdzərəm /). Unsur, berat-blok keperakan-perak, merkuri adalah satu-satunya elemen logam yang cair pada kondisi standar untuk suhu dan tekanan; satu-satunya unsur lain yang cair dalam kondisi ini adalah brom, meskipun logam seperti cesium, gallium, dan rubidium meleleh tepat di atas suhu kamar.')
    tab3.title('Nomor Atom:')
    tab3.write('80')
    tab3.title('Massa Atom Relatif:')
    tab3.write('200.592560642052(g/mol)')
    tab3.title('Densitas, kg*m^-3:')
    tab3.write('13.534(Kg/m^3)')
    tab3.title('Titik Leleh:')
    tab3.write('-38.83°C = -37.89°F = 234.32 K')
    tab3.title('Titik didih:')
    tab3.write('356.73°C = 647.11°F = 629.88 K')
    tab3.title('Fase:')
    tab3.write('Cair')
    tab3.title('Periode:')
    tab3.write('6')

    tab4.title('Nama Latin:')
    tab4.write('Copernecium')
    tab4.title('Tahun ditemukan:')
    tab4.write('1996')
    tab4.title('Penemu:')
    tab4.write('GSI (Helmholtzzentrum fur Schwerionenforschung')
    tab4.title('Catatan:')
    tab4.write('Copernicium adalah elemen kimia dengan simbol Cn dan nomor atom 112. Ini adalah elemen sintetis yang sangat radioaktif yang hanya dapat dibuat di laboratorium. Isotop yang diketahui paling stabil, copernicium-285, memiliki waktu paruh sekitar 29 detik, tetapi ada kemungkinan isotop copernicium ini mungkin memiliki isomer nuklir dengan waktu paruh lebih lama, 8,9 menit.')
    tab4.title('Nomor Atom:')
    tab4.write('112')
    tab4.title('Massa Atom Relatif:')
    tab4.write('286.093635599278(g/mol)')
    tab4.title('Densitas, kg*m^-3:')
    tab4.write('-')
    tab4.title('Titik Leleh:')
    tab4.write('10.0°C = 50.0°F = 283.15 K')
    tab4.title('Titik didih:')
    tab4.write('67.0°C = 152.6°F = 340.15 K')
    tab4.title('Fase:')
    tab4.write('Padat')
    tab4.title('Periode:')
    tab4.write('7')

elif option == "golongan IIIA":
    tab1,tab2,tab3,tab4,tab5,tab6=st.tabs(['Boron','Alumunium','Galium','Indium','Talium','Nihonium'])

    tab1.title('Nama Latin:')
    tab1.write('Borum')
    tab1.title('Tahun ditemukan:')
    tab1.write('1808')
    tab1.title('Penemu:')
    tab1.write('Joseph Louis Gay-Lussac,Louis Jasques Thenard, Humphry Davy')
    tab1.title('Catatan:')
    tab1.write('Boron adalah elemen kimia metalloid dengan simbol B dan nomor atom 5. Diproduksi sepenuhnya oleh spallation sinar kosmik dan supernova dan bukan oleh nukleosintesis bintang, ini adalah elemen dengan kelimpahan rendah di tata surya dan kerak bumi. Boron terkonsentrasi di Bumi oleh kelarutan dalam air dari senyawa yang terjadi secara umum, mineral borat.')
    tab1.title('Nomor Atom:')
    tab1.write('5')
    tab1.title('Massa Atom Relatif:')
    tab1.write('10.8135187949825(g/mol)')
    tab1.title('Densitas')
    tab1.write('2.34(g/cm^3)')
    tab1.title('Titik Leleh:')
    tab1.write('°2076.0C = 3768.8°F = 2349.15K')
    tab1.title('Titik didih:')
    tab1.write('3927°C = 7100.6°F = 4200.15K')
    tab1.title('Fase:')
    tab1.write('Padat')
    tab1.title('Periode:')
    tab1.write('2')

    tab2.title('Nama Latin:')
    tab2.write('Aluminium')
    tab2.title('Tahun ditemukan:')
    tab2.write('1825')
    tab2.title('Penemu:')
    tab2.write('Hans Christian Orsted')
    tab2.title('Catatan:')
    tab2.write('Aluminium (atau aluminium; lihat ujung yang berbeda) adalah unsur kimia dalam kelompok boron dengan simbol Al dan nomor atom 13. Ini adalah logam ulet berwarna putih keperakan, lunak, tidak magnetik, elastis. Aluminium adalah unsur ketiga yang paling melimpah (setelah oksigen dan silikon), dan logam yang paling melimpah, di kerak bumi.')
    tab2.title('Nomor Atom:')
    tab2.write('13')
    tab2.title('Massa Atom Relatif:')
    tab2.write('26.9815384123685(g/mol)')
    tab2.title('Densitas:')
    tab2.write('2.7(g/cm^3)')
    tab2.title('Titik Leleh:')
    tab2.write('°660.32C = 1220.58°F = 933.47K')
    tab2.title('Titik didih:')
    tab2.write('2470.0°C = 4478.0°F = 2743.15K')
    tab2.title('Fase:')
    tab2.write('Padat')
    tab2.title('Periode:')
    tab2.write('3')
    
    tab3.title('Nama Latin:')
    tab3.write('Gallium')
    tab3.title('Tahun ditemukan:')
    tab3.write('1875')
    tab3.title('Penemu:')
    tab3.write('Paul Emile Lecoq de Boisbaudran')
    tab3.title('Catatan:')
    tab3.write('Galium adalah unsur kimia dengan simbol Ga dan nomor atom 31. Galium unsur tidak terjadi dalam bentuk bebas di alam, tetapi sebagai galium (III) senyawa yang dalam jumlah jejak dalam bijih seng dan dalam bauksit. Gallium adalah logam lunak, berwarna keperakan, dan unsur gallium adalah zat padat rapuh pada suhu rendah, dan meleleh pada suhu 29,76° C (85,57° F) (sedikit di atas suhu kamar).')
    tab3.title('Nomor Atom:')
    tab3.write('31')
    tab3.title('Massa Atom Relatif:')
    tab3.write('69.7230661032944(g/mol)')
    tab3.title('Densitas:')
    tab3.write('5.91(g/cm^3)')
    tab3.title('Titik Leleh:')
    tab3.write('29.7646°C = 85.58°F = 302.91K')
    tab3.title('Titik didih:')
    tab3.write('2400.0°C = 4352.0°F = 2673.15K')
    tab3.title('Fase:')
    tab3.write('Padat')
    tab3.title('Periode:')
    tab3.write('4')

    tab4.title('Nama Latin:')
    tab4.write('Indium')
    tab4.title('Tahun ditemukan:')
    tab4.write('1863')
    tab4.title('Penemu:')
    tab4.write('Ferdinard Reich')
    tab4.title('Catatan:')
    tab4.write('Indium adalah elemen kimia dengan simbol In dan nomor atom 49. Ini adalah elemen logam pasca-transisi yang jarang terjadi di kerak bumi. Logam ini sangat lunak, mudah ditempa dan mudah melebur, dengan titik lebur lebih tinggi dari natrium, tetapi lebih rendah dari litium atau timah.')
    tab4.title('Nomor Atom:')
    tab4.write('49')
    tab4.title('Massa Atom Relatif:')
    tab4.write('114.818266549865(g/mol)')
    tab4.title('Densitas:')
    tab4.write('7.31(g/cm^3)')
    tab4.title('Titik Leleh:')
    tab4.write('156.6°C = 313.88°F = 429.75K')
    tab4.title('Titik didih:')
    tab4.write('2072.0°C = 3761.6°F = 2345.15K')
    tab4.title('Fase:')
    tab4.write('Padat')
    tab4.title('Periode:')
    tab4.write('5')

    
    tab5.title('Nama Latin:')
    tab5.write('Thalium')
    tab5.title('Tahun ditemukan:')
    tab5.write('1861')
    tab5.title('Penemu:')
    tab5.write('Wiliam Crookes')
    tab5.title('Catatan:')
    tab5.write('')
    tab5.title('Nomor Atom:')
    tab5.write('81')
    tab5.title('Massa Atom Relatif:')
    tab5.write('204.383512460528(g/mol)')
    tab5.title('Densitas:')
    tab5.write('11.85(g/cm^3)')
    tab5.title('Titik Leleh:')
    tab5.write('304.0°C = 579.2°F = 577.15K')
    tab5.title('Titik didih:')
    tab5.write('1473.0°C = 2683.4°F = 1746.15K')
    tab5.title('Fase:')
    tab5.write('Padat')
    tab5.title('Periode:')
    tab5.write('6')

    tab6.title('Nama Latin:')
    tab6.write('Nihonium')
    tab6.title('Tahun ditemukan:')
    tab6.write('2003')
    tab6.title('Penemu:')
    tab6.write('RIKEN (理研)')
    tab6.title('Catatan:')
    tab6.write('')
    tab6.title('Nomor Atom:')
    tab6.write('113')
    tab6.title('Massa Atom Relatif:')
    tab6.write('287.998233477411(g/mol)')
    tab6.title('Densitas:')
    tab6.write('-')
    tab6.title('Titik Leleh:')
    tab6.write('430.0°C = 806.0°F = 703.15K')
    tab6.title('Titik didih:')
    tab6.write('1130.0°C = 2066.0°F = 1403.15K')
    tab6.title('Fase:')
    tab6.write('Padat')
    tab6.title('Periode:')
    tab6.write('7')

elif option == "golongan IVA":
    tab1,tab2,tab3,tab4,tab5,tab6=st.tabs(['Karbon','Silikon','Germanium','Timah','Timbal','Flerovium'])
    tab1.title('Nama Latin:')
    tab1.write('Carbonium (Carboneum)')
    tab1.title('Tahun ditemukan:')
    tab1.write('3750 BC')
    tab1.title('Penemu:')
    tab1.write('Antoine Laurent de Lavoisier')
    tab1.title('Catatan:')
    tab1.write('Karbon adalah elemen kimia dengan simbol C dan nomor atom 6. Pada tabel periodik, ini adalah yang pertama (baris 2) dari enam elemen dalam kolom (grup) 14, yang memiliki kesamaan komposisi kulit elektron luarnya. Ini bukan logam dan tetravalen membuat empat elektron tersedia untuk membentuk ikatan kimia kovalen.')
    tab1.title('Nomor Atom:')
    tab1.write('6')
    tab1.title('Massa Atom Relatif:')
    tab1.write('12.0106355612542(g/mol)')
    tab1.title('Densitas')
    tab1.write('2.267 (g/cm^3)')
    tab1.title('Titik Leleh:')
    tab1.write('3527.0°C =6380.6°F =3800.15 K ')
    tab1.title('Titik didih:')
    tab1.write('3915.0°C =7079.0°F =4188.15 K')
    tab1.title('Fase:')
    tab1.write('Padat')
    tab1.title('Periode:')
    tab1.write('2')

    tab2.title('Nama Latin:')
    tab2.write('Silicium')
    tab2.title('Tahun ditemukan:')
    tab2.write('1823')
    tab2.title('Penemu:')
    tab2.write('Jons Jakob Berzelius')
    tab2.title('Catatan:')
    tab2.write('Silikon adalah elemen kimia dengan simbol Si dan nomor atom 14. Ini adalah metaloid tetravalen, lebih reaktif daripada germanium, metaloid langsung di bawahnya dalam tabel. Kontroversi tentang tanggal karakter silikon hingga penemuannya.')
    tab2.title('Nomor Atom:')
    tab2.write('14')
    tab2.title('Massa Atom Relatif:')
    tab2.write('28.0849993456101 (g/mol)')
    tab2.title('Densitas')
    tab2.write('2.33(g/cm^3)')
    tab2.title('Titik Leleh:')
    tab2.write('1414.0°C =2577.2°F =1687.15 K')
    tab2.title('Titik didih:')
    tab2.write('3265.0°C =5909.0°F =3538.15 K')
    tab2.title('Fase:')
    tab2.write('Padat')
    tab2.title('Periode:')
    tab2.write('3')
    
    tab3.title('Nama Latin:')
    tab3.write('Germanium')
    tab3.title('Tahun ditemukan:')
    tab3.write('1886')
    tab3.title('Penemu:')
    tab3.write('Clemes Alexander Winkler')
    tab3.title('Catatan:')
    tab3.write('Germanium adalah elemen kimia dengan simbol Ge dan nomor atom 32. Ini adalah metaloid berkilau, keras, putih keabu-abuan dalam kelompok karbon, secara kimiawi mirip dengan tetangganya, timah dan silikon. Germanium murni adalah semikonduktor, dengan penampilan yang paling mirip dengan silikon unsur.')
    tab3.title('Nomor Atom:')
    tab3.write('32')
    tab3.title('Massa Atom Relatif:')
    tab3.write('72.6298488671316(g/mol)')
    tab3.title('Densitas')
    tab3.write('5.323(g/cm^3)')
    tab3.title('Titik Leleh:')
    tab3.write('938.25°C =1720.85°F =1211.4 K')
    tab3.title('Titik didih:')
    tab3.write('2833.0°C =5131.4°F =3106.15 K')
    tab3.title('Fase:')
    tab3.write('Padat')
    tab3.title('Periode:')
    tab3.write('4')

    tab4.title('Nama Latin:')
    tab4.write('Stannum')
    tab4.title('Tahun ditemukan:')
    tab4.write('3500 BC')
    tab4.title('Penemu:')
    tab4.write('-')
    tab4.title('Catatan:')
    tab4.write('Timah adalah unsur kimia dengan simbol Sn dan nomor atom 50. Ini adalah logam grup utama dalam grup 14 dari tabel periodik. Timah menunjukkan kesamaan kimia dengan kedua unsur kelompok-14 yang berdekatan, germanium dan timbal, dan memiliki dua kemungkinan tingkat oksidasi, +2 dan +4 yang sedikit lebih stabil.')
    tab4.title('Nomor Atom:')
    tab4.write('50')
    tab4.title('Massa Atom Relatif:')
    tab4.write('118.71011319607g/mol')
    tab4.title('Densitas')
    tab4.write('7.265(g/cm^3)')
    tab4.title('Titik Leleh:')
    tab4.write('231.93°C =449.47°F =505.08K')
    tab4.title('Titik didih:')
    tab4.write('2602.0°C =4715.6°F =2875.15K')
    tab4.title('Fase:')
    tab4.write('Padat')
    tab4.title('Periode:')
    tab4.write('5')

    tab5.title('Nama Latin:')
    tab5.write('Plumbum')
    tab5.title('Tahun ditemukan:')
    tab5.write('7000 BC')
    tab5.title('Penemu:')
    tab5.write('-')
    tab5.title('Catatan:')
    tab5.write('Timbal adalah unsur kimia dalam kelompok karbon dengan simbol Pb (dari bahasa Latin: timbal) dan nomor atom 82. Timbal adalah logam pasca-transisi yang lunak, lunak dan berat. Timbal metalik memiliki warna putih kebiru-biruan setelah dipotong baru-baru ini, tetapi segera berubah menjadi warna abu-abu kusam saat terpapar ke udara.')
    tab5.title('Nomor Atom:')
    tab5.write('82')
    tab5.title('Massa Atom Relatif:')
    tab5.write('207.216907578328(g/mol)')
    tab5.title('Densitas:')
    tab5.write('11.34(g/cm^3)')
    tab5.title('Titik Leleh:')
    tab5.write('327.46°C =621.43°F =600.61K')
    tab5.title('Titik didih:')
    tab5.write('1749.0°C =3180.2°F =2022.15K')
    tab5.title('Fase:')
    tab5.write('Padat')
    tab5.title('Periode:')
    tab5.write('6')

    tab6.title('Nama Latin:')
    tab6.write('Flerovium')
    tab6.title('Tahun ditemukan:')
    tab6.write('1998')
    tab6.title('Penemu:')
    tab6.write('Joint Institute for Nucklear Research (JINR)')
    tab6.title('Catatan:')
    tab6.write('Flerovium adalah unsur kimia buatan superheavy dengan simbol Fl dan nomor atom 114. Flerovium adalah unsur sintetis yang sangat radioaktif. Unsur ini dinamai Laboratorium Flerov Reaksi Nuklir dari Institut Gabungan untuk Penelitian Nuklir di Dubna, Rusia, tempat unsur itu ditemukan pada tahun 1998.')
    tab6.title('Nomor Atom:')
    tab6.write('114')
    tab6.title('Massa Atom Relatif:')
    tab6.write('290.217148623513(g/mol)')
    tab6.title('Densitas:')
    tab6.write('-')
    tab6.title('Titik Leleh:')
    tab6.write('-73.0°C =-99.4°F =200.15K')
    tab6.title('Titik didih:')
    tab6.write('107.0°C =224.6°F =380.15K')
    tab6.title('Fase:')
    tab6.write('Padat')
    tab6.title('Periode:')
    tab6.write('7')

elif option == "golongan VA":
    tab1,tab2,tab3,tab4,tab5,tab6=st.tabs(['Nitrogen','Fosfor','Arsen','Antimon','Bismut','Moskovium'])

    tab1.title('Nama Latin:')
    tab1.write('Nitrogenium')
    tab1.title('Tahun ditemukan:')
    tab1.write('1772')
    tab1.title('Penemu:')
    tab1.write('Daniel Rutherford')
    tab1.title('Catatan:')
    tab1.write('Nitrogen adalah elemen kimia dengan simbol N dan nomor atom 7. Ini adalah pnictogen paling ringan dan pada suhu kamar, itu adalah gas diatomik transparan dan tidak berbau. Nitrogen adalah elemen umum di alam semesta, diperkirakan sekitar ketujuh total kelimpahan di Bima Sakti dan Tata Surya.')
    tab1.title('Nomor Atom:')
    tab1.write('7')
    tab1.title('Massa Atom Relatif:')
    tab1.write('14.0068577516411(g/mol)')
    tab1.title('Densitas:')
    tab1.write('0.001251(g/cm^3)')
    tab1.title('Titik Leleh:')
    tab1.write('-210.0°C = -346.0°F = 63.15K')
    tab1.title('Titik didih:')
    tab1.write('-195.795°C = 320.43°F =77.35K')
    tab1.title('Fase:')
    tab1.write('Gas')
    tab1.title('Periode:')
    tab1.write('2')

    tab2.title('Nama Latin:')
    tab2.write('Phosphorus')
    tab2.title('Tahun ditemukan:')
    tab2.write('1669')
    tab2.title('Penemu:')
    tab2.write('Henning Brand')
    tab2.title('Catatan:')
    tab2.write('Fosfor adalah zat yang menunjukkan fenomena luminesensi; ia memancarkan cahaya ketika terkena beberapa jenis energi radiasi. Istilah ini digunakan baik untuk zat fluoresen ataupun fosforesen yang bersinar pada paparan sinar ultraviolet atau cahaya tampak, dan zat katodoluminesen yang bersinar ketika dihantam oleh berkas elektron (sinar katode) dalam tabung sinar katode.')
    tab2.title('Nomor Atom:')
    tab2.write('15')
    tab2.title('Massa Atom Relatif:')
    tab2.write('30.9737619977018(g/mol)')
    tab2.title('Densitas')
    tab2.write('1.823(g/cm^3)')
    tab2.title('Titik Leleh:')
    tab2.write('44.15°C =111.47°F =317.3K')
    tab2.title('Titik didih:')
    tab2.write('277.0°C =530.6°F =550.15K')
    tab2.title('Fase:')
    tab2.write('Padat')
    tab2.title('Periode:')
    tab2.write('3')
    
    tab3.title('Nama Latin:')
    tab3.write('Arsenicum')
    tab3.title('Tahun ditemukan:')
    tab3.write('815 AD')
    tab3.title('Penemu:')
    tab3.write('Albertus Magnus')
    tab3.title('Catatan:')
    tab3.write('Arsenik adalah unsur kimia dengan lambang As dan nomor atom 33. Arsen terdapat dalam banyak mineral, biasanya dalam kombinasi dengan belerang dan beberapa logam, tetapi juga sebagai kristal elemental murni. Arsen adalah sebuah metaloid. Ia memiliki berbagai alotrop, tetapi hanya bentuk abu-abu, yang memiliki penampilan metalik, yang penting bagi industri.')
    tab3.title('Nomor Atom:')
    tab3.write('33')
    tab3.title('Massa Atom Relatif:')
    tab3.write('74.921594565322(g/mol)')
    tab3.title('Densitas:')
    tab3.write('5.727(g/cm^3)')
    tab3.title('Titik Leleh:')
    tab3.write('817.0°C = 1502.6°F = 1090.15K')
    tab3.title('Titik didih:')
    tab3.write('614.0°C = 1137°F = 887.15K')
    tab3.title('Fase:')
    tab3.write('Padat')
    tab3.title('Periode:')
    tab3.write('4')

    tab4.title('Nama Latin:')
    tab4.write('Stibium')
    tab4.title('Tahun ditemukan:')
    tab4.write('815 AD')
    tab4.title('Penemu:')
    tab4.write('Basil Valentine')
    tab4.title('Catatan:')
    tab4.write('Antimon adalah suatu unsur kimia dalam tabel periodik yang memiliki lambang Sb dan nomor atom 51. Lambangnya diambil dari bahasa Latin Stibium. Antimon merupakan metaloid dan mempunyai empat alotropi bentuk. Bentuk stabil antimon adalah logam biru-putih. Antimoni kuning dan hitam adalah logam tak stabil. Antimon digunakan sebagai bahan tahan api, cat, keramik, elektronik, dan karet.')
    tab4.title('Nomor Atom:')
    tab4.write('51')
    tab4.title('Massa Atom Relatif:')
    tab4.write('121.759784168018 (g/mol)')
    tab4.title('Densitas:')
    tab4.write('6.697(g/cm^3)')
    tab4.title('Titik Leleh:')
    tab4.write('630.63°C = 1167.13°F = 903.78K')
    tab4.title('Titik didih:')
    tab4.write('1635.0°C = 2975.0°F = 1908.15K')
    tab4.title('Fase:')
    tab4.write('Padat')
    tab4.title('Periode:')
    tab4.write('5')

    tab5.title('Nama Latin:')
    tab5.write('Bisemutum (Bismutthum, Bismutum) ')
    tab5.title('Tahun ditemukan:')
    tab5.write('1000 AD')
    tab5.title('Penemu:')
    tab5.write('Claude Francois Geoffrey')
    tab5.title('Catatan:')
    tab5.write('Bismut atau timah wurung adalah sebuah unsur kimia dengan lambang Bi dan nomor atom 83. Bismut adalah sebuah logam pascatransisi dan salah satu pniktogen, dengan sifat kimianya menyerupai saudara golongan 15-nya yang lebih ringan, arsen dan antimon. Bismut elemental terjadi secara alami, dan bentuk sulfida dan oksidanya merupakan bijih komersial yang penting.')
    tab5.title('Nomor Atom:')
    tab5.write('83')
    tab5.title('Massa Atom Relatif:')
    tab5.write('208.980398587653 (g/mol)')
    tab5.title('Densitas:')
    tab5.write('9.78(g/cm^3)')
    tab5.title('Titik Leleh:')
    tab5.write('271.5°C = 520.7°F = 544.65K')
    tab5.title('Titik didih:')
    tab5.write('1564.0°C = 2847.2°F = 1837.15K')
    tab5.title('Fase:')
    tab5.write('Padat')
    tab5.title('Periode:')
    tab5.write('6')

    tab6.title('Nama Latin:')
    tab6.write('Moscovium')
    tab6.title('Tahun ditemukan:')
    tab6.write('2003')
    tab6.title('Penemu:')
    tab6.write('Joint Institute for Nuclear Research (JINR), Lawrence Livermore National Laboratory (LLNL)')
    tab6.title('Catatan:')
    tab6.write('Livermorium adalah elemen superheavy sintetis dengan simbol Lv dan nomor atom 116. Ini adalah elemen yang sangat radioaktif yang hanya dibuat di laboratorium dan belum diamati di alam. Unsur ini dinamai Laboratorium Nasional Lawrence Livermore di Amerika Serikat, yang bekerja sama dengan Institut Gabungan untuk Penelitian Nuklir di Dubna, Rusia untuk menemukan livermorium pada tahun 2000.')
    tab6.title('Nomor Atom:')
    tab6.write('115')
    tab6.title('Massa Atom Relatif:')
    tab6.write('291.54205471157(g/mol)')
    tab6.title('Densitas:')
    tab6.write('-')
    tab6.title('Titik Leleh:')
    tab6.write('400°C = 752.0°F = 673.15K')
    tab6.title('Titik didih:')
    tab6.write('1100.0°C = 2012.0°F = 1373.15K')
    tab6.title('Fase:')
    tab6.write('Padat')
    tab6.title('Periode:')
    tab6.write('7')

elif option == "golongan VIA":
    tab1,tab2,tab3,tab4,tab5,tab6=st.tabs(['Oksigen','Sulfur','Selenium','Telurium','Polonium','Livermorium'])
    tab1.title('Nama Latin:')
    tab1.write('Oxygenium')
    tab1.title('Tahun ditemukan:')
    tab1.write('1771')
    tab1.title('Penemu:')
    tab1.write('Michał Sędziwój, Joseph Priestley, Carl Wilhelm Scheele')
    tab1.title('Catatan:')
    tab1.write('Oksigen adalah unsur kimia dengan simbol O dan nomor atom 8. la adalah anggota kelompok kalkogen pada tabel periodik dan merupakan zat bukan-oksidasi dan oksidator yang sangat reaktif yang siap membentuk senyawa (terutama oksida) dengan sebagian besar unsur. Secara massal, oksigen adalah unsur ketiga terbanyak di alam semesta, setelah hidrogen dan helium.')
    tab1.title('Nomor Atom:')
    tab1.write('8')
    tab1.title('Massa Atom Relatif:')
    tab1.write('999404924080(g/mol)')
    tab1.title('Densitas:')
    tab1.write('0.001429 (g/cm^3)')
    tab1.title('Titik Leleh:')
    tab1.write('-218.79°C =-361.82°F =54.36K')
    tab1.title('Titik didih:')
    tab1.write('-182.962°C =-297.33°F =90.19K')
    tab1.title('Fase:')
    tab1.write('Gas')
    tab1.title('Periode:')
    tab1.write('2')

    tab2.title('Nama Latin:')
    tab2.write('Sulphuris')
    tab2.title('Tahun ditemukan:')
    tab2.write('2000 BC')
    tab2.title('Penemu:')
    tab2.write('-')
    tab2.title('Catatan:')
    tab2.write('Belerang atau belerang (lihat perbedaan ejaan) adalah elemen kimia dengan simbol S dan nomor atom 16. Ini adalah unsur non-logam yang banyak dan multivalen. Dalam kondisi normal, atom belerang membentuk molekul oktomik siklik dengan rumus kimia S8.')
    tab2.title('Nomor Atom:')
    tab2.write('16')
    tab2.title('Massa Atom Relatif:')
    tab2.write('064787405621(g/mol)')
    tab2.title('Densitas:')
    tab2.write('2.070(g/cm^3)')
    tab2.title('Titik Leleh:')
    tab2.write('112.8°C =235.04°F =385.95K')
    tab2.title('Titik didih:')
    tab2.write('444.6°C =832.28°F =717.75K')
    tab2.title('Fase:')
    tab2.write('Padat')
    tab2.title('Periode:')
    tab2.write('3')
    
    tab3.title('Nama Latin:')
    tab3.write('Selenium')
    tab3.title('Tahun ditemukan:')
    tab3.write('1817')
    tab3.title('Penemu:')
    tab3.write('Jöns Jakob Berzelius')
    tab3.title('Catatan:')
    tab3.write('Selenium adalah unsur kimia dengan simbol Se dan nomor atom 34. Selenium adalah unsur non-logam yang sifatnya menengah antara elemen-elemen kalkogen yang berdekatan dengan kolom tabel, yaitu sulfur dan telurium. Jarang terjadi pada keadaan unsurnya di alam, atau sebagai senyawa bijih murni.')
    tab3.title('Nomor Atom:')
    tab3.write('34')
    tab3.title('Massa Atom Relatif:')
    tab3.write('78.971081481700(g/mol)')
    tab3.title('Densitas:')
    tab3.write('4.81(g/cm^3)')
    tab3.title('Titik Leleh:')
    tab3.write('221.0°C =429.8°F =494.15K')
    tab3.title('Titik didih:')
    tab3.write('685.0°C =1265.0°F =958.15K')
    tab3.title('Fase:')
    tab3.write('Padat')
    tab3.title('Periode:')
    tab3.write('4')

    tab4.title('Nama Latin:')
    tab4.write('Tellurium')
    tab4.title('Tahun ditemukan:')
    tab4.write('1782')
    tab4.title('Penemu:')
    tab4.write('-')
    tab4.title('Catatan:')
    tab4.write('Tellurium adalah unsur kimia dengan simbol Te dan nomor atom 52. Ini adalah logam yang rapuh, agak beracun, jarang, berwarna perak-putih. Tellurium secara kimiawi terkait dengan selenium dan belerang.')
    tab4.title('Nomor Atom:')
    tab4.write('52')
    tab4.title('Massa Atom Relatif:')
    tab4.write('127.603126893528(g/mol)')
    tab4.title('Densitas:')
    tab4.write('6.24 (g/cm^3)')
    tab4.title('Titik Leleh:')
    tab4.write('449.51°C =841.12°F =722.66K')
    tab4.title('Titik didih:')
    tab4.write('988.0°C =1810.4°F =1261.15K')
    tab4.title('Fase:')
    tab4.write('Padat')
    tab4.title('Periode:')
    tab4.write('5')


    tab5.title('Nama Latin:')
    tab5.write('Polonium ')
    tab5.title('Tahun ditemukan:')
    tab5.write('1898')
    tab5.title('Penemu:')
    tab5.write('Pierre Curie, Marie Skłodowska Curie')
    tab5.title('Catatan:')
    tab5.write('Polonium adalah unsur kimia dengan simbol Po dan nomor atom 84, ditemukan pada tahun 1898 oleh Marie Curie dan Pierre Curie. Unsur radioaktif yang langka dan sangat radioaktif tanpa isotop stabil, polonium secara kimiawi mirip dengan bismut dan telurium, dan itu terjadi dalam bijih uranium. Aplikasi polonium sedikit.')
    tab5.title('Nomor Atom:')
    tab5.write('84')
    tab5.title('Massa Atom Relatif:')
    tab5.write('208.962006199874 (g/mol)')
    tab5.title('Densitas:')
    tab5.write('9.196(g/cm^3)')
    tab5.title('Titik Leleh:')
    tab5.write('254.0°C =489.2°F =527.15K')
    tab5.title('Titik didih:')
    tab5.write('962.0°C =1763.6°F =1235.15K')
    tab5.title('Fase:')
    tab5.write('Padat')
    tab5.title('Periode:')
    tab5.write('6')

    tab6.title('Nama Latin:')
    tab6.write('Livermorium')
    tab6.title('Tahun ditemukan:')
    tab6.write('2000')
    tab6.title('Penemu:')
    tab6.write('Joint Institute for Nuclear Research (JINR), Lawrence Livermore National Laboratory (LLNL)')
    tab6.title('Catatan:')
    tab6.write('Livermorium adalah elemen superheavy sintetis dengan simbol Lv dan nomor atom 116. Ini adalah elemen yang sangat radioaktif yang hanya dibuat di laboratorium dan belum diamati di alam. Unsur ini dinamai Laboratorium Nasional Lawrence Livermore di Amerika Serikat, yang bekerja sama dengan Institut Gabungan untuk Penelitian Nuklir di Dubna, Rusia untuk menemukan livermorium pada tahun 2000.')
    tab6.title('Nomor Atom:')
    tab6.write('116')
    tab6.title('Massa Atom Relatif:')
    tab6.write('292.470799589671 (g/mol)')
    tab6.title('Densitas:')
    tab6.write('-')
    tab6.title('Titik Leleh:')
    tab6.write('435.5°C =815.9°F =708.65K')
    tab6.title('Titik didih:')
    tab6.write('812.0°C =1493.6°F =1085.15k')
    tab6.title('Fase:')
    tab6.write('Padat')
    tab6.title('Periode:')
    tab6.write('7')

elif option == "golongan VIIA":
    tab1,tab2,tab3,tab4,tab5,tab6=st.tabs(['Fluor','Klor','Brom','Yodium','Astatin','Tenesin'])
    tab1.title('Nama Latin:')
    tab1.write('Fluorum')
    tab1.title('Tahun ditemukan:')
    tab1.write('1810')
    tab1.title('Penemu:')
    tab1.write('Ferdinand Frederic Henri Moissan')
    tab1.title('Catatan:')
    tab1.write('Fluor adalah elemen kimia dengan simbol F dan nomor atom 9. Ini adalah halogen paling ringan dan ada sebagai gas diatomik kuning pucat yang sangat beracun pada kondisi standar. Sebagai unsur yang paling elektronegatif, ia sangat reaktif: hampir semua unsur lain, termasuk beberapa gas mulia, membentuk senyawa dengan fluor.')
    tab1.title('Nomor Atom:')
    tab1.write('9')
    tab1.title('Massa Atom Relatif:')
    tab1.write('18.9984031620854(g/mol)')
    tab1.title('Densitas:')
    tab1.write('0.0017(g/cm^3)')
    tab1.title('Titik Leleh:')
    tab1.write('-219.67°C =-363.41°F =53.48K')
    tab1.title('Titik didih:')
    tab1.write('-188.11°C =-306.6°F =85.04K')
    tab1.title('Fase:')
    tab1.write('Gas')
    tab1.title('Periode:')
    tab1.write('2')

    tab2.title('Nama Latin:')
    tab2.write('Chlorum')
    tab2.title('Tahun ditemukan:')
    tab2.write('1774')
    tab2.title('Penemu:')
    tab2.write('Carl Wilhelm Scheele')
    tab2.title('Catatan:')
    tab2.write('Klorin adalah unsur kimia dengan simbol Cl dan nomor atom 17. la juga memiliki massa atom relatif 35,5. Klorin berada dalam kelompok halogen (17) dan merupakan halogen paling ringan kedua setelah fluor.')
    tab2.title('Nomor Atom:')
    tab2.write('17')
    tab2.title('Massa Atom Relatif:')
    tab2.write('35.4521387667802(g/mol)')
    tab2.title('Densitas:')
    tab2.write('0.0032(g/cm^3)')
    tab2.title('Titik Leleh:')
    tab2.write('-101.5°C =-150.7°F =171.65 K')
    tab2.title('Titik didih:')
    tab2.write('-34.04°C =-29.27°F =239.11 K')
    tab2.title('Fase:')
    tab2.write('Gas')
    tab2.title('Periode:')
    tab2.write('3')
    
    tab3.title('Nama Latin:')
    tab3.write('Bromun')
    tab3.title('Tahun ditemukan:')
    tab3.write('1826')
    tab3.title('Penemu:')
    tab3.write('Antoine-jerome balard,Karl jacob leuwich')
    tab3.title('Catatan:')
    tab3.write('Brom adalah elemen kimia dengan simbol Br, dan nomor atom 35. Ini adalah halogen. Unsur itu diisolasi secara independen oleh dua ahli kimia, Carl Jacob Löwig dan Antoine Jerome Balard, pada tahun 1825-1826.')
    tab3.title('Nomor Atom:')
    tab3.write('35')
    tab3.title('Massa Atom Relatif:')
    tab3.write('79.9043261630963(g/mol)')
    tab3.title('Densitas:')
    tab3.write('3.1028 (g/cm^3)')
    tab3.title('Titik Leleh:')
    tab3.write('-7.3°C =18.86°F =265.85K')
    tab3.title('Titik didih:')
    tab3.write('58.8°C =137.84°F =331.95 K')
    tab3.title('Fase:')
    tab3.write('Cair')
    tab3.title('Periode:')
    tab3.write('4')

    tab4.title('Nama Latin:')
    tab4.write('Iodium')
    tab4.title('Tahun ditemukan:')
    tab4.write('1811')
    tab4.title('Penemu:')
    tab4.write('Bernard Courtois')
    tab4.title('Catatan:')
    tab4.write('Yodium adalah elemen kimia dengan simbol I dan nomor atom 53. Namanya berasal dari bahasa Yunani ἰοειδής ioeidēs, yang berarti violet atau ungu, karena warna uap yodium. Yodium dan senyawanya terutama digunakan dalam nutrisi, dan secara industri dalam produksi asam asetat dan polimer tertentu.')
    tab4.title('Nomor Atom:')
    tab4.write('53')
    tab4.title('Massa Atom Relatif:')
    tab4.write('126.904472825143(g/mol)')
    tab4.title('Densitas:')
    tab4.write('4.933(g/cm^3)')
    tab4.title('Titik Leleh:')
    tab4.write('113.7°C = 236.66°F = 386.86K')
    tab4.title('Titik didih:')
    tab4.write('184.3°C = 363.74°F = 457.45K')
    tab4.title('Fase:')
    tab4.write('Padat')
    tab4.title('Periode:')
    tab4.write('5')

    tab5.title('Nama Latin:')
    tab5.write('Astatum')
    tab5.title('Tahun ditemukan:')
    tab5.write('1940')
    tab5.title('Penemu:')
    tab5.write('Paul Emile Lecoq de Boisbaudran')
    tab5.title('Catatan:')
    tab5.write('Astatin adalah unsur kimia radioaktif yang sangat langka dengan lambang kimia At dan nomor atom 85. Astatin terjadi di Bumi sebagai produk peluruhan berbagai unsur yang lebih berat. Semua isotopnya berumur pendek; yang paling stabil adalah astatin-210, dengan paruh 8,1 jam..')
    tab5.title('Nomor Atom:')
    tab5.write('85')
    tab5.title('Massa Atom Relatif:')
    tab5.write('209.602075361333(g/mol)')
    tab5.title('Densitas:')
    tab5.write('7.0(g/cm^3)')
    tab5.title('Titik Leleh:')
    tab5.write('302.0°C = 575.6°F = 575.15K')
    tab5.title('Titik didih:')
    tab5.write('336.8°C = 638.24°F = 609.95K')
    tab5.title('Fase:')
    tab5.write('Padat')
    tab5.title('Periode:')
    tab5.write('6')

    tab6.title('Nama Latin:')
    tab6.write('Tennessine')
    tab6.title('Tahun ditemukan:')
    tab6.write('2010')
    tab6.title('Penemu:')
    tab6.write('Joint Institute for Nuclear Research (JINR)')
    tab6.title('Catatan:')
    tab6.write('Tennessine adalah unsur kimia buatan superheavy dengan nomor atom 117 dan simbol Ts. Juga dikenal sebagai eka-astatin atau elemen 117, itu adalah elemen yang diketahui paling berat kedua dan elemen kedua terakhir dari periode ke-7 dari tabel periodik. Pada 2016, lima belas atom tennessine telah diamati: enam ketika pertama kali disintesis pada tahun 2010, tujuh pada 2012, dan dua pada 2014.')
    tab6.title('Nomor Atom:')
    tab6.write('117')
    tab6.title('Massa Atom Relatif:')
    tab6.write('293.73334018093(g/mol)')
    tab6.title('Densitas:')
    tab6.write('-')
    tab6.title('Titik Leleh:')
    tab6.write('450.0°C = 842.0°F = 723.15K')
    tab6.title('Titik didih:')
    tab6.write('610.0°C = 1130.0°F = 883.15K')
    tab6.title('Fase:')
    tab6.write('Padat')
    tab6.title('Periode:')
    tab6.write('7')

elif option == "golongan VIIIA":
    tab1,tab2,tab3,tab4,tab5,tab6=st.tabs(['Helium','Neon','Argon','Krypton','Xenon','Radon'])
    tab1.title('Nama Latin:')
    tab1.write('Helium')
    tab1.title('Tahun ditemukan:')
    tab1.write('1868')
    tab1.title('Penemu:')
    tab1.write('Pierre Jules César Janssen & Joseph Norman Lockyer')
    tab1.title('Catatan:')
    tab1.write('Helium adalah suatu unsur kimia;  ia memiliki simbol He dan nomor atom 2. Ia adalah gas monatomik yang tidak berwarna, tidak berbau, tidak berasa, tidak beracun, inert, dan merupakan yang pertama dalam kelompok gas mulia dalam tabel periodikTitik didihnya paling rendah di antara semuanya.unsur-unsurnya, dan tidak memiliki titik leleh pada tekanan standar. Ini adalah unsur paling ringan kedua dan paling melimpah kedua di alam semesta yang dapat diamati, setelah hidrogen. Ia hadir di sekitar 24% dari total massa unsur, yang lebih dari 12 kali massa gabungan semua unsur yang lebih berat. Kelimpahannya serupa dengan kelimpahan di Matahari dan Yupiter, karena energi ikat inti (per nukleon) helium-4 yang sangat tinggi, dibandingkan dengan tiga unsur berikutnya setelah helium.  Energi pengikatan helium-4 ini juga menjelaskan mengapa helium-4 merupakan produk fusi nuklir dan peluruhan radioaktif.  Isotop helium yang paling umum di alam semesta adalah helium-4, yang sebagian besar terbentuk selama Big Bang. Helium baru dalam jumlah besar dihasilkan oleh fusi nuklir hidrogen di bintang.')
    tab1.title('Nomor Atom:')
    tab1.write('2')
    tab1.title('Massa Atom Relatif:')
    tab1.write('4.00260128098301(g/mol)')
    tab1.title('Densitas:')
    tab1.write('0.0001786 (g/cm^3)')
    tab1.title('Titik Leleh:')
    tab1.write('-273.15°C = -459.67°F = 0.0K')
    tab1.title('Titik didih:')
    tab1.write('-268.928°C = -452.07°F = 4.22K')
    tab1.title('Fase:')
    tab1.write('Gas')
    tab1.title('Periode:')
    tab1.write('1')

    tab2.title('Nama Latin:')
    tab2.write('Neon')
    tab2.title('Tahun ditemukan:')
    tab2.write('1898')
    tab2.title('Penemu:')
    tab2.write('Sir William Ramsay & Morris William Traves')
    tab2.title('Catatan:')
    tab2.write('Neon adalah unsur kimia;  ia memiliki simbol Ne dan nomor atom 10. Ia adalah gas mulia kedua dalam tabel periodik. [13] Neon adalah gas monatomik inert yang tidak berwarna, tidak berbau, dalam kondisi standar, dengan kepadatan sekitar dua pertiga udara.')
    tab2.title('Nomor Atom:')
    tab2.write('10')
    tab2.title('Massa Atom Relatif:')
    tab2.write('20.1800463795723 (g/mol)')
    tab2.title('Densitas:')
    tab2.write('0.0009002(g/cm^3)')
    tab2.title('Titik Leleh:')
    tab2.write('-248.59°C = -415.46°F = 24.56K')
    tab2.title('Titik didih:')
    tab2.write('-246.046°C = -410.88°F = 27.1K')
    tab2.title('Fase:')
    tab2.write('Gas')
    tab2.title('Periode:')
    tab2.write('2')
    
    tab3.title('Nama Latin:')
    tab3.write('Argon')
    tab3.title('Tahun ditemukan:')
    tab3.write('1894')
    tab3.title('Penemu:')
    tab3.write('Sir William Ramsay')
    tab3.title('Catatan:')
    tab3.write('Argon adalah unsur kimia;  ia memiliki simbol Ar dan nomor atom 18. Ia berada di golongan 18 tabel periodik dan merupakan gas mulia.  Argon adalah gas ketiga terbanyak di atmosfer bumi, sebesar 0,934% (9340 ppmv). Jumlahnya dua kali lebih banyak dibandingkan uap air (rata-rata sekitar 4000 ppmv, namun sangat bervariasi), 23 kali lebih banyak dibandingkan karbon dioksida (400 ppmv), dan lebih dari 500 kali lebih banyak dibandingkan neon (18 ppmv).  Argon adalah gas mulia yang paling melimpah di kerak bumi, mencakup 0,00015% kerak bumi.')
    tab3.title('Nomor Atom:')
    tab3.write('18')
    tab3.title('Massa Atom Relatif:')
    tab3.write('39.9477985618953 (g/mol)')
    tab3.title('Densitas:')
    tab3.write('0.001784(g/cm^3)')
    tab3.title('Titik Leleh:')
    tab3.write('-189.34°C = -308.81°F = 83.81K')
    tab3.title('Titik didih:')
    tab3.write('-185.848°C = -302.53°F = 87.3K')
    tab3.title('Fase:')
    tab3.write('Gas')
    tab3.title('Periode:')
    tab3.write('3')

    tab4.title('Nama Latin:')
    tab4.write('Krypton')
    tab4.title('Tahun ditemukan:')
    tab4.write('1898')
    tab4.title('Penemu:')
    tab4.write('Sir William Ramsay & Morris William Traves')
    tab4.title('Catatan:')
    tab4.write('Krypton (dari bahasa Yunani Kuno: κρυπτός, diromanisasi: kryptos (yang tersembunyi)) adalah suatu unsur kimia;  ia memiliki simbol Kr dan nomor atom 36. Ini adalah gas mulia yang tidak berwarna, tidak berbau, dan tidak berasa yang terdapat dalam jumlah kecil di atmosfer dan sering digunakan dengan gas langka lainnya dalam lampu neon. Krypton bersifat inert secara kimia.')
    tab4.title('Nomor Atom:')
    tab4.write('36')
    tab4.title('Massa Atom Relatif:')
    tab4.write('83.7979997384043 (g/mol)')
    tab4.title('Densitas:')
    tab4.write('0.003749 (g/cm^3)')
    tab4.title('Titik Leleh:')
    tab4.write('-157.37°C = -251.27°F = 115.78K')
    tab4.title('Titik didih:')
    tab4.write('-153.415°C = -244.15°F = 119.74K')
    tab4.title('Fase:')
    tab4.write('Gas')
    tab4.title('Periode:')
    tab4.write('4')

    tab5.title('Nama Latin:')
    tab5.write('Xenon')
    tab5.title('Tahun ditemukan:')
    tab5.write('1898')
    tab5.title('Penemu:')
    tab5.write('Sir William Ramsay & Morris William Traves')
    tab5.title('Catatan:')
    tab5.write('Xenon adalah unsur kimia; ia memiliki simbol Xe dan nomor atom 54. Ia adalah gas mulia padat, tidak berwarna, dan tidak berbau yang ditemukan di atmosfer bumi dalam jumlah kecil. Meskipun umumnya tidak reaktif, ia dapat mengalami beberapa reaksi kimia seperti pembentukan xenon heksafluoroplatinat, senyawa gas mulia pertama yang disintesis.')
    tab5.title('Nomor Atom:')
    tab5.write('54')
    tab5.title('Massa Atom Relatif:')
    tab5.write('131.29277126863 (g/mol)')
    tab5.title('Densitas:')
    tab5.write('0.003749 (g/cm^3)')
    tab5.title('Titik Leleh:')
    tab5.write('-111.75°C = -169.15°F = 161.4K')
    tab5.title('Titik didih:')
    tab5.write('-108.099°C = -162.58°F = 165.05K')
    tab5.title('Fase:')
    tab5.write('Gas')
    tab5.title('Periode:')
    tab5.write('5')

    tab6.title('Nama Latin:')
    tab6.write('Radon')
    tab6.title('Tahun ditemukan:')
    tab6.write('1899')
    tab6.title('Penemu:')
    tab6.write('Friedrich Ernst Dorn')
    tab6.title('Catatan:')
    tab6.write('Radon adalah unsur kimia;  ia memiliki simbol Rn dan nomor atom 86. Ia adalah gas mulia radioaktif dan tidak berwarna serta tidak berbau. Dari tiga isotop radon yang terbentuk secara alami, hanya radon-222 yang memiliki waktu paruh yang cukup lama (3,825 hari) untuk dilepaskan dari tanah dan batuan tempat ia dihasilkan. Isotop radon adalah produk peluruhan langsung dari isotop radium. Ketidakstabilan radon-222, isotopnya yang paling stabil, menjadikan radon salah satu unsur paling langka. Radon akan berada di Bumi selama beberapa miliar tahun lagi, meskipun waktu paruhnya pendek, karena ia terus-menerus diproduksi sebagai bagian dari rantai peluruhan uranium-238, dan thorium-232, yang masing-masing merupakan rantai peluruhan yang sangat ekstrim. Nuklida radioaktif yang berlimpah dengan waktu paruh beberapa miliar tahun.  Peluruhan radon menghasilkan banyak nuklida berumur pendek lainnya, yang dikenal sebagai "anak perempuan radon", yang berakhir pada isotop timbal yang stabil.Radon-222 terjadi dalam jumlah yang signifikan sebagai langkah dalam rantai peluruhan radioaktif normal uranium-238, juga dikenal sebagai seri uranium, yang perlahan-lahan meluruh menjadi berbagai nuklida radioaktif dan akhirnya meluruh menjadi timbal-206, yang stabil. Radon-220 terjadi dalam jumlah kecil sebagai langkah perantara dalam rantai peluruhan thorium-232, juga dikenal sebagai rangkaian thorium, yang akhirnya terurai menjadi timbal-208, yang stabil.')
    tab6.title('Nomor Atom:')
    tab6.write('86')
    tab6.title('Massa Atom Relatif:')
    tab6.write('220.190117161994 (g/mol)')
    tab6.title('Densitas:')
    tab6.write('0.00973 (g/cm^3)')
    tab6.title('Titik Leleh:')
    tab6.write('-71.0°C = -95.8°F = 202.15K')
    tab6.title('Titik didih:')
    tab6.write('-61.7°C = -79.06°F = 211.45K')
    tab6.title('Fase:')
    tab6.write('Gas')
    tab6.title('Periode:')
    tab6.write('6')
